authelia/authelia

src/index.js

* Do not display config information during boot
* Avoid ECONNRESET failures by setting reconnect option to true and handling error events

Do not display config and resolve ECONNRESET failure

---

Gruntfile.js
scripts/dc-dev.sh
src/client/css/01-main.css
src/client/css/02-login.css
src/server/views/layout/layout.pug

Add "Powered by Authelia" with a link to the framework at the bottom of each page.

Add "Powered by Authelia" at the bottom of the web pages

---

Gruntfile.js
config.template.yml
config.test.yml
package.json
server/src/lib/IdentityCheckMiddleware.ts
server/src/lib/Server.ts
server/src/lib/configuration/Configuration.d.ts
server/src/lib/configuration/Configuration.schema.json
server/src/lib/configuration/ConfigurationAdapter.ts
server/src/lib/configuration/ConfigurationParser.ts
server/src/lib/configuration/Validator.ts
server/src/lib/notifiers/AbstractEmailNotifier.ts
server/src/lib/notifiers/FileSystemNotifier.ts
server/src/lib/notifiers/GMailNotifier.ts
server/src/lib/notifiers/INotifier.d.ts
server/src/lib/notifiers/INotifier.ts
server/src/lib/notifiers/SmtpNotifier.ts
server/test/ServerConfiguration.test.ts
server/test/configuration/ConfigurationAdapter.test.ts
server/test/configuration/ConfigurationParser.test.ts
server/test/configuration/LdapConfigurationAdaptation.test.ts
server/test/configuration/Validator.test.ts
server/test/notifiers/GMailNotifier.test.ts
server/test/notifiers/MailSenderBuilder.test.ts
server/test/notifiers/NotifierFactory.test.ts
server/test/server/PrivatePages.ts
server/test/server/PublicPages.ts

I also added a configuration validator at startup so that a user can quickly see a problem with his configuration before going any further.

Specify mail sender for SMTP and Gmail notifiers

---

example/nginx/html/home.test.local/index.html

Add information about fake webmail in home page

Add information about fake webmail in home page

---

server/src/lib/authentication/totp/ITotpHandler.ts
server/src/lib/authentication/totp/TotpHandler.ts
server/src/lib/configuration/Configuration.d.ts
server/src/lib/configuration/ConfigurationParser.ts
server/src/lib/configuration/adapters/TOTPAdapter.ts
server/src/lib/routes/secondfactor/totp/identity/RegistrationHandler.ts
server/src/lib/web_server/RestApi.ts
server/test/SessionConfigurationBuilder.test.ts
server/test/mocks/ServerVariablesMockBuilder.ts
server/test/mocks/TotpHandlerStub.ts
server/test/routes/secondfactor/totp/register/RegistrationHandler.test.ts
test/features/registration.feature
test/features/step_definitions/hooks.ts
test/features/step_definitions/registration.ts

Issuer is customizable in configuration so that a company can set its own name
or website. If not provided, default value is 'authelia.com'.
The username is used as label.

Use issuer and label when generating otpauthURL for TOTP

---

server/src/lib/IdentityCheckMiddleware.ts
server/src/lib/routes/password-reset/identity/PasswordResetHandler.ts
server/test/IdentityCheckMiddleware.test.ts
server/test/routes/password-reset/identity/PasswordResetHandler.test.ts

Reset password sends 200 status codes to avoid user enumeration.

Reset password form sends 200 status when user does not exist

---

.travis.yml
client/src/index.ts
package-lock.json
package.json
server/src/views/layout/layout.pug
server/src/views/secondfactor.pug

A link to U2F explains what is a U2F security key and how they are used.
A tooltip on U2F device registration link is telling the user he needs a
security key to register.

Add links and tooltips at second factor stage to better guide the user

---

config.template.yml
server/src/lib/configuration/SessionConfigurationBuilder.spec.ts
server/src/lib/configuration/SessionConfigurationBuilder.ts
server/src/lib/configuration/schema/SessionConfiguration.spec.ts
server/src/lib/configuration/schema/SessionConfiguration.ts
test/features/forward-headers.feature
test/features/step_definitions/forward-headers.ts

This option is optional and set to authelia_session
by default.

Make session cookie name customizable.

---

config.template.yml
example/compose/mongo/docker-compose.yml
example/compose/redis/docker-compose.yml
server/src/lib/IdentityCheckMiddleware.spec.ts
server/src/lib/IdentityCheckMiddleware.ts
server/src/lib/IdentityValidableStub.spec.ts
server/src/lib/ServerVariablesInitializer.ts
server/src/lib/configuration/SessionConfigurationBuilder.spec.ts
server/src/lib/configuration/SessionConfigurationBuilder.ts
server/src/lib/configuration/schema/SessionConfiguration.ts
server/src/lib/configuration/schema/StorageConfiguration.ts
server/src/lib/connectors/mongo/MongoClient.spec.ts
server/src/lib/connectors/mongo/MongoClient.ts
test/features/step_definitions/hooks.ts

Enable authentication to Mongo and Redis.

---

Dockerfile.dev
Gruntfile.js
client/src/css/02-login.css
client/src/lib/firstfactor/FirstFactorValidator.ts
client/src/lib/firstfactor/UISelectors.ts
client/src/lib/firstfactor/index.ts
client/test/firstfactor/FirstFactorValidator.test.ts
config.minimal.yml
docker-compose.dev.yml
docker-compose.test.yml
package-lock.json
server/src/lib/AuthenticationSessionHandler.ts
server/src/lib/routes/firstfactor/post.spec.ts
server/src/lib/routes/firstfactor/post.ts
server/src/lib/routes/verify/get.spec.ts
server/src/lib/routes/verify/get_session_cookie.ts
server/src/lib/storage/mongo/MongoCollection.ts
server/src/views/firstfactor.pug
server/types/AuthenticationSession.ts
test/configuration.ts
test/environment.ts
test/helpers/fill-login-page-and-click.ts
test/inactivity/00-suite.ts
test/inactivity/keep_me_logged_in.ts
test/minimal-config/validate_totp.ts

This is a pain to be asked every time a session expires to log in again when we're on "trusted devices".
Now, one could check the "keep me logged in" checkbox to extend the cookie expiry date to 1 year and disable inactivity timeout for this session.

Add a "keep me logged in" checkbox.

---

Gruntfile.js
client/src/lib/SafeRedirect.ts
client/src/lib/firstfactor/index.ts
client/src/lib/secondfactor/U2FValidator.ts
client/src/lib/secondfactor/index.ts
client/src/lib/u2f-register/u2f-register.ts
server/src/lib/routes/firstfactor/get.ts
server/src/lib/routes/firstfactor/post.ts
server/src/lib/routes/secondfactor/u2f/sign_request/get.ts
server/src/lib/routes/verify/get_basic_auth.ts
server/src/lib/routes/verify/get_session_cookie.ts
server/src/lib/utils/DomainExtractor.ts
server/src/lib/utils/SafeRedirection.spec.ts
server/src/lib/utils/SafeRedirection.ts
server/src/views/secondfactor.pug
shared/BelongToDomain.ts
shared/DomainExtractor.spec.ts
shared/DomainExtractor.ts
shared/UserMessages.ts
test/complete-config/closed-redirection.ts
test/complete-config/mongo-broken-connection.ts
test/environment.ts
test/helpers/full-login.ts
test/helpers/login-and-register-totp.ts
test/helpers/login-as.ts
test/minimal-config/bad_password.ts
test/minimal-config/fail_totp.ts
test/minimal-config/reset_password.ts
test/minimal-config/validate_totp.ts

In order to redirect the user after authentication, Authelia uses
rd query parameter provided by the proxy. However an attacker could
use phishing to make the user be redirected to a bad domain.
In order to avoid the user to be redirected to a bad location, Authelia now
verifies the redirection URL is under the protected domain.

Fix open redirection vulnerability.

---

server/src/lib/authentication/backends/file/FileUsersDatabase.ts

This fixes #315 by modifing the regex to allow the character ".".

Modified regex in file database mode

---

docs/deployment-dev.md

Hello,
I only fixed a dead link in the deployment-dev file because it didn't work when I clicked on it :)
Cheers!

Fix dead link in docs/deployment-dev.md

---

docs/proxies/nginx.md

This is to ensure that the proxies documentation for nginx is in-line with the latest breaking changes that have been made.
The existing examples no longer will work, and will result in a blank redirection.

Update doc/proxies/nginx.md examples

---

server/src/resources/email-template.ejs

It's safer to tell the user that the operation is abnormal in the case he have not initiated the process. So we tell him what to do: reset the password and contact and admin to track down the attacker.

Update email footer to inform about a potential compromise

---

CHANGELOG.md
Dockerfile
authentication/file_user_provider.go
authentication/password_hash.go
authentication/password_hash_test.go
cmd/authelia-scripts/cmd_hash_password.go
go.mod
go.sum

Use pure implementation of crypt to generate and check password hashes.

Use pure implementation of crypt to generate and check password hashes.

---

cmd/authelia-scripts/cmd_bootstrap.go
cmd/authelia-scripts/cmd_docker.go
docs/authelia-scripts.md
docs/build-and-dev.md
docs/deployment-dev.md
docs/deployment-production.md
docs/getting-started.md
docs/security.md
docs/suites.md
example/compose/authelia/docker-compose.yml
example/compose/nginx/backend/html/home/index.html
test/helpers/GetIdentityLink.ts
test/helpers/scenarii/TwoFactorAuthentication.ts
test/suites/docker-image/README.md
test/suites/docker-image/config.yml
test/suites/docker-image/environment.ts
test/suites/docker-image/test.ts

Running this suite is the first advice given by the
bootstrap script to help the user move forward.
This commit also updates the documentation to reflect
changes introduced by the Go rewrite.

Create suite for testing the docker image.

---

cmd/authelia-scripts/cmd_docker.go

This time actually fix the manifest.

Fix docker manifest

---

cmd/authelia-scripts/cmd_docker.go

Publish additional minor and major tags on DockerHub

---

.travis.yml

You need to configure your `GITHUB_API_KEY` in [Travis](https://stackoverflow.com/questions/23277391/how-to-publish-to-github-pages-from-travis-ci).
Closes #457.

Publish binary artifacts to GitHub

---

cmd/authelia-scripts/cmd_suites.go

Optimize test time by reusing docker layers in each containers.

Be able to multiple selected suites with authelia-scripts

---

internal/storage/postgres_provider.go
internal/storage/sql_provider.go

- column name is second_factor_method, not method

Fix PostgreSQL Update Second Factor Method Pref

---

.buildkite/hooks/post-checkout

Fixes Buildkite integration test steps.

Allow authelia-scripts to be called in e2etest setup

---

.buildkite/hooks/pre-artifact
.buildkite/hooks/pre-command
.buildkite/pipeline.yml
.buildkite/steps/buildimages.sh
.buildkite/steps/ghartifacts.sh
.travis.yml

Slightly higher compression rate and is significantly faster than gzip.

Utilise zstd for compression

---

.buildkite/hooks/post-command
.buildkite/hooks/pre-artifact
.buildkite/pipeline.yml
.travis.yml

Buildkite optimise agents

---

BREAKING.md
cmd/authelia-scripts/migration_local.go
cmd/authelia-scripts/migration_mongo.go
docs/proxies/nginx.md
example/kube/README.md
example/kube/apps/apps.yml
internal/configuration/schema/notifier.go
internal/handlers/handler_extended_configuration.go
internal/handlers/handler_user_info.go
internal/handlers/handler_user_info_test.go
internal/handlers/types.go
internal/notification/smtp_notifier.go
internal/regulation/regulator_test.go
internal/storage/provider.go
internal/storage/provider_mock.go
internal/storage/sql_provider.go
internal/templates/email.go
web/src/services/UserPreferences.ts
web/src/views/LoginPortal/SecondFactor/SecondFactorForm.tsx

Fix spelling errors and update nginx docs

---

Dockerfile
Dockerfile.arm32v7
Dockerfile.arm64v8
cmd/authelia-scripts/cmd_docker.go
cmd/authelia/main.go

Add git tag back to binary artifact.

---

docs/proxies/nginx.md
docs/proxies/traefik1.x.md
docs/proxies/traefik2.x.md

Includes updated documentation for:
- nginx
- Traefik 1.x
- Traefik 2.x

[MISC] Update docs to include updated proxy configuration

---

.buildkite/hooks/post-checkout
.buildkite/hooks/post-command
.buildkite/hooks/pre-artifact
.buildkite/hooks/pre-command
.buildkite/pipeline.yml
.buildkite/steps/buildimages.sh
cmd/authelia-scripts/cmd_docker.go

This change will now deploy a Docker image for every submitted PR and Branch, they can be pulled from the following annotations:
`authelia/authelia:branch-name-here`
`authelia/authelia:PRNNN`
This gives us the ability to quickly roll out changes during troubleshooting and development cycles.
Once a PR is merged or closed or a branch is deleted, the respective tag from Docker Hub will also be removed.
Last step should be to provision/deploy an auto-comment bot to announce the annotation to pull the container specifically within the PR.

[Buildkite] Automatic deployment and removal of Docker images for Branches and PRs

---

.buildkite/deployment.yml
.buildkite/pipeline.yml

This PR improves the security of our Buildkite pipeline to not allow leakage of secrets.
Some additional steps have already been implemented upstream, this is the final piece of the puzzle required within the repo.
An example of the block can be viewed at: #597 and https://buildkite.com/authelia/authelia/builds/290

[Buildkite] Re-order pipeline to improve security

---

bootstrap.sh

[MISC] Make bootstrap.sh OSX friendly

---

internal/handlers/const.go
internal/handlers/errors.go
internal/handlers/handler_verify.go
internal/handlers/handler_verify_test.go

This PR improves the documentation around the verify endpoint to facilitate integration by providing clear error messages.
It would have been useful in cases like https://github.com/authelia/authelia/issues/618.

[MISC] Improve documentation around headers used by verify endpoint.

---

internal/configuration/schema/configuration.go
internal/configuration/validator/configuration.go
internal/configuration/validator/configuration_test.go
internal/configuration/validator/storage.go
internal/configuration/validator/storage_test.go

This PR will fix the core dump mentioned in https://github.com/authelia/authelia/issues/622.
This PR also fix the Google analytics configuration.

[FIX] Prevent crash when storage config is nil

---

internal/authorization/authorizer.go
internal/authorization/authorizer_test.go
internal/authorization/domain_matcher.go
internal/authorization/domain_matcher_test.go
internal/authorization/ip_matcher.go
internal/authorization/ip_matcher_test.go
internal/authorization/path_matcher.go
internal/authorization/path_matcher_test.go
internal/authorization/subject_matcher.go

[MISC] Add unit tests to authorization module and trace logs.

---

internal/handlers/handler_verify.go
internal/handlers/handler_verify_test.go

Fixes #655 
No idea if this is how you would approach it - this is my kneejerk reaction to solving it. Please feel free to close / modify at will.

[FEATURE] Support secure websocket connections.

---

.buildkite/deployment.yml
.buildkite/steps/ghartifacts.sh

This is to handle failures which may occur when attempting to upload assets, per: https://buildkite.com/authelia/authelia/builds/465#537f931f-efc3-4f7b-9527-c927c1425a52.

[Buildkite] Enable automatic retries for failed github artifact step

---

docs/configuration/index.md
docs/configuration/storage/index.md
docs/deployment/deployment-ha.md
docs/deployment/deployment-lite.md
docs/features/2fa/push-notifications.md
docs/features/access-control.md
docs/features/regulation.md
docs/features/single-factor.md
docs/getting-started.md
docs/index.md

[DOCS] Fix Docs Links

---

cmd/authelia/main.go
docs/deployment/deployment-lite.md
docs/home/architecture.md
internal/commands/certificates.go

[FEATURE] Add command to generate self-signed certs in authelia binary.

---

.buildkite/hooks/post-checkout
.buildkite/steps/aurhelper.sh
.buildkite/steps/ghartifacts.sh

This will ensure that we always will have up-to-date refs for the repo post-checkout.

[Buildkite] Reorder git fetch in pipeline

---

.buildkite/deployment.sh

Minor tweak to skip the whole deployment pipeline rather than individual steps.

[Buildkite] Adjust pipeline for dependabot

---

config.template.yml
docs/configuration/one-time-password.md
go.mod
go.sum
internal/configuration/schema/totp.go
internal/configuration/validator/configuration.go
internal/configuration/validator/totp.go
internal/configuration/validator/totp_test.go
internal/handlers/handler_extended_configuration.go
internal/handlers/handler_extended_configuration_test.go
internal/handlers/handler_register_totp.go
internal/handlers/handler_sign_totp.go
internal/handlers/handler_sign_totp_test.go
internal/handlers/totp.go
internal/handlers/totp_mock.go
internal/server/server.go
web/src/components/PieChartIcon.tsx
web/src/components/TimerIcon.tsx
web/src/models/Configuration.ts
web/src/services/Configuration.ts
web/src/views/LoginPortal/SecondFactor/OTPDial.tsx
web/src/views/LoginPortal/SecondFactor/OneTimePasswordMethod.tsx
web/src/views/LoginPortal/SecondFactor/SecondFactorForm.tsx

[FEATURE] TOTP Tuning Configuration Options

---

.buildkite/pipeline.sh

Looks like I missed one of the wait steps in my original PR to fix this.
You can see the extra wait block in [this build](https://buildkite.com/authelia/authelia/builds/1028).
This is purely aesthetic and not a functional change.

[Buildkite] Tweak pipeline to conditionally ignore a wait step

---

.buildkite/steps/ghartifacts.sh
BREAKING.md

This will ensure that notes pertaining to a version in the BREAKING.md will be published in each of the respective github releases.
All information from:
'## Breaking in $TAG' until the next '## Breaking in $TAG' is included.

[Buildkite] Add contents of BREAKING.md for tag to releases

---

config.template.yml
docs/configuration/authentication/file.md
docs/configuration/authentication/index.md
docs/configuration/authentication/ldap.md
docs/security/measures.md
internal/configuration/schema/authentication.go
internal/configuration/validator/authentication.go
internal/handlers/handler_configuration.go
internal/handlers/handler_configuration_test.go
internal/server/server.go
web/src/App.tsx
web/src/models/Configuration.ts
web/src/views/LoginPortal/FirstFactor/FirstFactorForm.tsx
web/src/views/LoginPortal/LoginPortal.tsx

[FEATURE] Disable Reset Password

---

docs/configuration/access-control.md
docs/configuration/authentication/file.md
docs/configuration/authentication/ldap.md
docs/configuration/duo-push-notifications.md
docs/configuration/google-analytics.md
docs/configuration/miscellaneous.md
docs/configuration/notifier/filesystem.md
docs/configuration/notifier/smtp.md
docs/configuration/one-time-password.md
docs/configuration/regulation.md
docs/configuration/storage/mariadb.md
docs/configuration/storage/mysql.md
docs/configuration/storage/postgres.md
docs/configuration/storage/sqlite.md
docs/contributing/authelia-scripts.md
docs/contributing/suites.md
docs/features/password-reset.md
docs/security/index.md

* use two spaces
* use yaml syntax highlighting

[DOCS] Adjust yaml snippets and misc adjustments

---

config.template.yml
docs/configuration/authentication/ldap.md

[DOCS] Improve documentation about users unique identifier.

---

.github/probot.js

* thank users for their contribution
* let users know about the golangci-lint reviews
* notify users about artifacts on buildkite

[CI] Update PR commentary messages

---

.github/probot.js
cmd/authelia/main.go
config.template.yml
docs/configuration/notifier/filesystem.md
docs/configuration/notifier/index.md
docs/configuration/notifier/smtp.md
internal/configuration/schema/notifier.go
internal/configuration/validator/notifier.go
internal/mocks/mock_notifier.go
internal/notification/const.go
internal/notification/file_notifier.go
internal/notification/notifier.go
internal/notification/smtp_notifier.go
internal/suites/DuoPush/configuration.yml
internal/suites/OneFactorOnly/configuration.yml

[FEATURE] Notifier Startup Checks

---

internal/notification/smtp_notifier.go

[MISC] Linting Unparam Fixes

---

.buildkite/hooks/post-command
.buildkite/pipeline.sh

This utilises the GitHub checks API and could be a potential candidate instead of in-line PR reviews.

[CI] Introduce linting for branch commits with reviewdog

---

cmd/authelia/main.go
config.template.yml
docs/configuration/index.md
go.sum
internal/commands/validate.go
internal/configuration/reader.go
internal/configuration/reader_test.go
internal/configuration/test_resources/config_bad_keys.yml
internal/configuration/validator/const.go
internal/configuration/validator/keys.go
internal/configuration/validator/keys_test.go

Didn't spend much time on this, and we didn't really agree on a design in advance so see what you think.
If a key doesn't exist in the list in const.go it will fail unless it's in the map. The map is used to configure custom errors in the situations where we expect people may get it wrong and to give specific advice.
* check configuration for invalid keys on startup
* allow users to manually trigger all configuration validation on a file using a cmd
* setup all defaults in config template and run tests against it to prevent accidents
* use tests to check bad configuration values are caught
* use tests to check old configuration values are caught
Closes #776

[FEATURE] Config Validation

---

internal/notification/const.go
internal/notification/file_notifier.go
internal/notification/smtp_notifier.go

* set to 0600 for security
As discussed with Clement.

[FIX] File Notifier Default Permissions

---

Dockerfile
Dockerfile.arm32v7
Dockerfile.arm64v8
Dockerfile.darwin
internal/suites/example/compose/kind/Dockerfile

update to alpine 3.11.6 for latest security updates.
Signed-off-by: Daniel Sutton <daniel@ducksecops.uk>

[MISC] Update to alpine 3.11.6

---

docs/deployment/supported-proxies/haproxy.md

This includes example on how to run Authelia with HAProxy.

[DOCS] Update proxy integration example for HAProxy

---

internal/server/server.go

[SECURITY] Disable HTTP Server Header

---

README.md
SECURITY.md
internal/authentication/file_user_provider.go
internal/authentication/file_user_provider_test.go
internal/authentication/ldap_user_provider.go
internal/authentication/password_hash.go

Temporarily addresses #949. Should not close the issue due to:
1. A proper fix being released.
2. People need to be aware they need to update.
* thanks to @TheHllm for identifying the bug: https://github.com/TheHllm
* temporarily prevents username enumeration with file auth
* proper calculated and very slightly random fix to come

[HOTFIX] Prevent Username Enumeration

---

docs/deployment/supported-proxies/nginx.md

[DOCS] Harmonize Remote-User and Remote-Groups headers in nginx example

---

internal/server/server.go

[BUGFIX] Add routes for files in the root path

---

compose/lite/configuration.yml

[BUGFIX] Prevent lite bundle redis panic

---

docs/deployment/supported-proxies/traefik2.x.md

[DOCS] Add FAQs to Traefik2

---

docs/_config.yml

This will allow us to analyze how the documentation is used in order to improve it
accordingly.

[DOCS] Add google analytics tracking to the documentation.

---

compose/local/authelia/configuration.yml
compose/local/authelia/users_database.yml

This is also to address a regression from #1113.
Fixes #1129.

[BUGFIX] Re-add local compose configuration files

---

internal/server/server.go

This change instructs Authelia to listen on `tcp` instead of `tcp4` which is the default for fasthttp.
This will allow Authelia to bind and listen on both IPv4 and/or IPv6 interfaces.
Closes #1189.

[FEATURE] Add IPv6 support

---

docs/deployment/supported-proxies/haproxy.md
internal/suites/example/compose/haproxy/Dockerfile
internal/suites/example/compose/haproxy/auth-request.lua
internal/suites/example/compose/haproxy/docker-compose.yml
internal/suites/example/compose/haproxy/haproxy.cfg
internal/suites/example/compose/haproxy/http.lua

This version removes the dependency of `lua-socket` which seemed restrictive for BSD/Pfsense deployments.
Fixes #1247.
Closes #1273.

[FEATURE] Support updated haproxy-auth-request

---

docs/deployment/supported-proxies/haproxy.md
internal/suites/example/compose/haproxy/haproxy.cfg

This also includes updates to docs examples.
Fixes #1331.

[BUGFIX] Fix HAProxy redirects

---

docs/deployment/supported-proxies/haproxy.md
internal/suites/example/compose/haproxy/haproxy.cfg

Remove headers that are not required and fix a typo.

[DOCS] Clean HAProxy examples

---

web/src/components/FixedTextField.tsx
web/src/views/LoginPortal/FirstFactor/FirstFactorForm.tsx

[MISC] Disable auto capitalization of username field on mobile

---

.buildkite/hooks/post-command

This is to support the codecov team in identifying and resolving an issue.

[CI] Run codecov in verbose mode

---

docs/configuration/access-control.md

[DOCS] Clarify use of multiple subjects in ACLs and their logical evaluation

---

internal/suites/suite_network_acl_test.go
internal/suites/utils.go
internal/suites/webdriver.go

This change aims to factorize code introduced in #1467 for webdriver port customisation within the suites.

[MISC] Refactor webdriver port initialization

---

.buildkite/RELEASE.md

[RELEASE] v4.24.0

---

docs/configuration/authentication/file.md

[DOCS] Update hash-password example with single quotes

---

config.template.yml
docs/configuration/authentication/ldap.md
docs/configuration/miscellaneous.md
docs/configuration/notifier/smtp.md
docs/configuration/session.md
docs/configuration/storage/mariadb.md
docs/configuration/storage/mysql.md
docs/configuration/storage/postgres.md

[DOCS] Add notes for IPv6 literal address

---

Dockerfile.coverage

Instead of mocking the index.html and openapi.yml copy the actual files across.

[CI] Simplify coverage Dockerfile

---

cmd/authelia/main.go
internal/authentication/file_user_provider.go
internal/authentication/ldap_user_provider.go
internal/authorization/authorizer.go
internal/configuration/reader.go
internal/notification/smtp_notifier.go
internal/server/error_handler.go
internal/server/server.go
internal/server/template.go
internal/suites/suite_cli_test.go

* Add missing test for `authelia version` command in CLI suite.
* Standardise logger calls.
* Swap CSP switch order to ensure correct CSP is applied in specific scenarios.

[MISC] Add missing CLI suite test 

---

.all-contributorsrc
README.md
docs/images/logos/goland.svg
docs/images/logos/intellij-idea.svg
docs/images/logos/jetbrains.svg
docs/images/logos/webstorm.svg

This change also modifies the contributors to introduce [All Contributors](https://allcontributors.org/).

[DOCS] Update contributors

---

.buildkite/pipeline.sh
.buildkite/steps/buildimages.sh
.buildkite/steps/e2etests.sh

ci(buildkite): change to concurrency gates

---

docs/deployment/supported-proxies/haproxy.md

The previous examples did not appropriately pass through the `WWW-Authenticate` header and 401 when the user was unauthenticated, therefore not resulting in a basic auth login prompt.

docs: fix haproxy examples for /api/verify?auth=basic

---

.buildkite/deployment.sh
.buildkite/pipeline.sh
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/misc.md

docs: add issue templates

---

.buildkite/hooks/post-command
.buildkite/steps/ghartifacts.sh
.github/probot.js
.golangci.yml
cmd/authelia-scripts/cmd_docker.go
cmd/authelia-scripts/const.go
cmd/authelia-scripts/docker.go

Publishes Docker container images on both DockerHub and GitHub Container Registry.
Closes #1614.

ci: publish docker images to ghcr

---

docs/community/index.md

docs: fix capitalization

---

go.mod
go.sum

Replaces github.com/dgrijalva/jwt-go with github.com/form3tech-oss/jwt-go.

build(deps): replace github.com/dgrijalva/jwt-go

---

.buildkite/pipeline.yml

This change updates the template for the hardcoded pipeline in Buildkite.

ci(buildkite): add notification webhook for blocked PRs

---

.buildkite/annotations/artifacts
.buildkite/deployment.sh
.buildkite/hooks/post-checkout
.buildkite/hooks/post-command
.buildkite/hooks/pre-artifact
.buildkite/hooks/pre-command
.buildkite/hooks/pre-exit
.buildkite/pipeline.sh
.buildkite/steps/aurhelper.sh
.buildkite/steps/buildimages.sh
.buildkite/steps/debhelper.sh
.buildkite/steps/debpackages.sh
.buildkite/steps/e2etests.sh
.buildkite/steps/ghartifacts.sh
README.md

Creates .deb packages for distribution via GitHub releases and Buildkite builds for the following architectures:
* amd64
* armhf
* arm64
Closes #573.

feat: build and distribute .deb packages

---

web/src/views/LoginPortal/FirstFactor/FirstFactorForm.tsx
web/src/views/ResetPassword/ResetPasswordStep2.tsx

Add autocomplete fields to first factor and reset password pages for auto filling.
See:
https://developer.apple.com/documentation/security/password_autofill/enabling_password_autofill_on_an_html_input_element

feat(web): provide autocomplete attributes

---

internal/authentication/const.go

This is the correct OID for the passwdModify Extended Operation.

fix(authentication): use passwdmodify oid instead of whoami oid

---

.buildkite/deployment.sh
.buildkite/hooks/pre-command
.buildkite/steps/aptdeploy.sh
.buildkite/steps/ghartifacts.sh
README.md
docs/images/logos/balto.svg

This automates the process of publishing our `*.deb` files for stable Authelia releases to apt.authelia.com.

feat: publish and deploy to apt.authelia.com

---

docs/_layouts/default.html
docs/configuration/access-control.md
docs/configuration/identity-providers/oidc.md
docs/configuration/index.md
docs/configuration/storage/sqlite.md
docs/deployment/deployment-ha.md
docs/features/2fa/security-key.md
docs/features/password-reset.md

This fixes misc broken links in the docs as well as an invalid viewBox element.

docs: misc fixes

---

docs/community/oidc-integrations.md

Very minor doc update.
See minio/minio#12722. Updated callback URL and issue description.

Update OIDC MinIO community content

---

docs/community/oidc-integrations.md

Clarifies minio/minio#12722 and updates the docs accordingly on how to use Authelia with MinIO.

Update community OIDC information

---

docs/configuration/identity-providers/oidc.md

Fix a few missing spaces in the documentation.

docs(oidc): fix links

---

README.md
cmd/authelia-scripts/cmd_docker.go
cmd/authelia-scripts/docker.go

MicroBadger is dead, so we need to remove all references of it.

fix(cmd): remove microbadger references

---

config.template.yml
docs/configuration/storage/mariadb.md
docs/configuration/storage/mysql.md
docs/configuration/storage/postgres.md
internal/configuration/config.template.yml
internal/configuration/schema/storage.go
internal/configuration/validator/const.go
internal/configuration/validator/storage.go
internal/storage/mysql_provider.go
internal/storage/postgres_provider.go

This sets a sane default connection timeout for SQL connections.

fix(storage): set sane default connection timeout

---

.buildkite/pipeline.sh
.buildkite/steps/buildimages.sh

If a commit message includes either `[skip-test]` or `[test-skip]` a some CI steps will be ignored.
This is to allow rapid deployments and prototyping when attempting fixes, under no circumstances should any PR to master be accepted with said tags/conditionals.

ci(buildkite): add [skip-test] and [test-skip] conditionals

---

docs/community/oidc-integrations.md

Quick PR to add the endpoints provided by @jasonmc1993 in [this issue](https://github.com/authelia/authelia/issues/2281). 
I tested Portainer on a local install and its working as expected.

docs: add wekan and portainer to community oidc list

---

docs/configuration/secrets.md

docs: fix typo in secrets env var

---

config.template.yml
internal/configuration/config.template.yml

This adds the redis sentinel username to the config templates.

docs(session): add redis sentinel username to config template

---

cmd/authelia-scripts/cmd_build.go

build(deps): update swagger-ui to v4.1.0

---

internal/storage/sql_provider_backend_postgres.go

Fixes an issue in the new storage system. We forgot to rebind the queries to the PostgreSQL compatible format.

fix(storage): rebind all queries

---

.github/ISSUE_TEMPLATE/config.yml
README.md
docs/about-us.md

This updates our matrix links to use the new Authelia homeserver.

docs: update matrix links

---

web/src/i18n/locales/es.json

translated oidc messages to spanish

feat(web): oidc i18n-es

---

docs/contributing/commitmsg-guidelines.md
internal/commands/root.go
web/.commitlintrc.js

Disable failure was ignored previously, this ensures it isn't.

fix(ntp): disable failure setting is ignored

---

docs/community/django-integration.md

Extend the information given at #2636 about how to integrate authelia with Django.

docs: add community example of integrating authelia with Django

---

docs/_config.yml

This fixes the incorrect year in the documentation.

docs: updated year

---

docs/configuration/session/index.md
internal/handlers/handler_firstfactor.go

This documents disabling remember me.

docs: add docs about remember me duration

---

config.template.yml
internal/configuration/config.template.yml
internal/configuration/validator/session.go
internal/configuration/validator/session_test.go

This allows users to disable remember me again.
Fixes #2978

fix(configuration): cannot disable remember me

---

internal/configuration/provider_test.go
internal/configuration/schema/const.go
internal/configuration/test_resources/config_alt.yml
internal/configuration/validator/session.go
internal/configuration/validator/session_test.go
internal/handlers/handler_firstfactor.go
internal/server/server.go

This fixes an issue not properly resolved by db6dd32151a8161e8348f32d19a687f0faa16ddf.
Fixes #2996

fix(configuration): remember me duration disabled impossible

---

docs/configuration/access-control.md

docs: adjust acl policy example to be possible

---

internal/handlers/handler_oidc_authorization.go
internal/handlers/handler_oidc_introspection.go
internal/handlers/handler_oidc_jwks.go
internal/handlers/handler_oidc_revocation.go
internal/handlers/handler_oidc_token.go
internal/handlers/handler_oidc_userinfo.go
internal/handlers/oidc.go
internal/oidc/types.go
internal/oidc/types_test.go

This adds significantly more detailed logging for most OpenID Connect handlers.

fix(oidc): add detailed trace/debug logs

---

internal/configuration/schema/authentication.go
internal/configuration/validator/const.go

This fixes an issue with key validation slice that has missing or extra keys that are not needed.

fix(configuration): incorrect key validation names

---

cmd/authelia-scripts/cmd_bootstrap.go
config.template.yml
docs/configuration/server.md
docs/security/measures.md
internal/commands/certificates.go
internal/commands/root.go
internal/configuration/config.template.yml
internal/configuration/schema/server.go
internal/configuration/validator/const.go
internal/configuration/validator/server.go
internal/configuration/validator/server_test.go
internal/server/const.go
internal/server/server.go
internal/server/server_test.go
internal/suites/environment.go
internal/suites/suite_cli_test.go
internal/utils/certificates.go
internal/utils/certificates_test.go

mutual tls prevent other clients than the proxies to communicate with Authelia. This reduces the attack
surface.
Fix #3041

feat: implement mutual tls in the web server

---

docs/deployment/deployment-kubernetes.md

Add some implementation notes about k8s.
Fixes #2882

docs: add k8s important notes

---

internal/suites/example/compose/nginx/portal/docker-compose.yml

@james-d-elliott : this PR reverts port binding in nginx config

suites: revert por binding

---

internal/configuration/validator/const.go

This fixes an issue with three missing config keys.

fix(configuration): missing valid keys

---

internal/suites/action_totp.go
internal/suites/scenario_one_factor_test.go
internal/suites/scenario_two_factor_test.go
internal/suites/suite_activedirectory_test.go
internal/suites/suite_docker_test.go
internal/suites/suite_haproxy_test.go
internal/suites/suite_high_availability_test.go
internal/suites/suite_kubernetes_test.go
internal/suites/suite_ldap_test.go
internal/suites/suite_mariadb_test.go
internal/suites/suite_mysql_test.go
internal/suites/suite_pathprefix_test.go
internal/suites/suite_postgres_test.go
internal/suites/suite_standalone_test.go
internal/suites/suite_traefik2_test.go
internal/suites/suite_traefik_test.go

* refactor(suites): mustpress -> mustinput for totp
* refactor(suites): rename suites for test ordering

test: add redis restart test back to traefik2 suite

---

internal/handlers/handler_reset_password_step2.go
internal/middlewares/identity_verification.go

This ensures all template types share the same template values and display them correctly regardless if text/html/other.
Fixes #3319

fix(handler): missing notification values

---

.editorconfig

This adjusts the editorconfig to be more reflective of the current style.

ci: fix editorconfig

---

.buildkite/hooks/pre-command
.buildkite/integration.sh
.buildkite/pipeline.sh
.buildkite/steps/e2etests.sh
internal/suites/example/compose/duo-api/Dockerfile
internal/suites/example/compose/duo-api/docker-compose.dev.yml
internal/suites/example/compose/duo-api/docker-compose.yml
internal/suites/example/compose/samba/Dockerfile
internal/suites/example/compose/samba/docker-compose.yml
internal/suites/suite_duo_push.go

This change utilises a specific integration container for the ActiveDirectory suite and simplifies the DuoPush suite.

ci: add integration container for samba and refactor duo

---

internal/storage/sql_provider_queries.go

Fixed typo in SQL UPDATE clause.

fix(storage): typo in oidc update query

---

internal/configuration/decode_hooks_test.go
internal/configuration/schema/types.go

Addresses code review for #3653.

refactor: address code review

---

docs/content/en/configuration/prologue/common.md

Tiny typo fix (but I noticed it so thought I may as well correct it!!)

tiny typo fix for common.md

---

README.md

https://www.authelia.com/overview/authentication/webauthn-security-key/ -> https://www.authelia.com/overview/authentication/security-key/

Fix 404 in readme

---

internal/logging/logger.go
internal/logging/printf.go
internal/server/server.go
internal/session/provider_config.go
internal/session/types.go

This implements and leverages some common library logging interfaces.

refactor(logging): implement common interfaces

---

docs/content/en/configuration/storage/introduction.md

small PR to fix a minor typo. :)

docs: fix typo in storage introduction file

---

docs/content/en/integration/prologue/get-started.md

docs: fix misc grammar issues

---

internal/handlers/handler_oidc_authorization.go
internal/middlewares/cors.go
internal/server/handlers.go

This fixes an issue where the authorization endpoint was not handling post requests as per the specification.

fix(oidc): handle authorization post requests

---

web/src/views/Settings/TwoFactorAuthentication/WebauthnDevices.tsx

feat: hide empty webauthn devices table when there are no devices

---

web/src/views/Settings/TwoFactorAuthentication/WebauthnDevices.tsx

(built on top of https://github.com/authelia/authelia/pull/4405)

feat: add loading skeleton to webauthn devices list in settings ui

---

web/src/services/Webauthn.ts
web/src/views/Settings/TwoFactorAuthentication/WebauthnDeviceDeleteDialog.tsx
web/src/views/Settings/TwoFactorAuthentication/WebauthnDeviceItem.tsx
web/src/views/Settings/TwoFactorAuthentication/WebauthnDevices.tsx

This branch is based off of https://github.com/authelia/authelia/pull/4406

feat: implement webauthn device delete confirmation

---

web/src/models/Webauthn.ts
web/src/services/Webauthn.ts
web/src/views/DeviceRegistration/RegisterWebauthn.tsx
web/src/views/Settings/TwoFactorAuthentication/WebauthnDeviceDeleteDialog.tsx
web/src/views/Settings/TwoFactorAuthentication/WebauthnDeviceEditDialog.tsx
web/src/views/Settings/TwoFactorAuthentication/WebauthnDeviceItem.tsx
web/src/views/Settings/TwoFactorAuthentication/WebauthnDevices.tsx

(built on top of https://github.com/authelia/authelia/pull/4406)

feat: implement webauthn device rename with dialog

---

web/src/layouts/SettingsLayout.tsx

refactor: retitle settings appbar to authelia settings

---

docs/content/en/configuration/second-factor/time-based-one-time-password.md

Updated the documentation with the missing user keyword

Updated the documentation

---

.renovaterc

ci: fix .renovaterc and add json schema

---

Dockerfile
Dockerfile.coverage
Dockerfile.dev
docs/content/en/configuration/methods/files.md
internal/commands/const.go
internal/commands/context.go
internal/commands/root.go
internal/commands/util.go
internal/suites/example/compose/authelia/Dockerfile.backend
internal/suites/example/compose/authelia/Dockerfile.frontend
internal/suites/example/compose/authelia/docker-compose.frontend.dev.yml
internal/suites/example/compose/authelia/resources/run-backend-dev.sh
internal/suites/suite_cli_test.go

This allows Authelia to discover config files and config options via environment variables.

feat(configuration): env config file discovery

---

internal/commands/root.go
internal/server/server.go
internal/templates/util_test.go
web/.env.production
web/index.html

This fixes a couple errors that were previously not logged or returned as well as ensuring most templates are appropriately parsed via tests.

fix(server): errors not logged

---

api/openapi.yml
internal/handlers/handler_oidc_wellknown.go
internal/server/asset.go
internal/server/handlers.go
internal/server/template.go
internal/suites/scenario_backend_protection_test.go
internal/suites/scenario_request_method_test.go
internal/suites/suite_standalone_test.go

This implements some HEAD method handlers for various static resources and the /api/health endpoint.

feat(server): handle head method

---

README.md
docs/content/en/configuration/identity-providers/open-id-connect.md
docs/content/en/contributing/development/environment.md
internal/authentication/ldap_client_mock.go
internal/authentication/types.go
internal/commands/const.go

This just implements some changes from feat-settings-ui that are out of scope.

refactor: misc out of band changes

---

docs/content/en/integration/openid-connect/tailscale/index.md

docs: misc fix

---

docs/content/en/configuration/second-factor/time-based-one-time-password.md
docs/content/en/reference/integrations/time-based-one-time-password-apps.md

Adds documentation for supported TOTP apps.
Closes #2650

docs: totp reference

---

internal/configuration/const.go
internal/configuration/decode_hooks.go
internal/configuration/decode_hooks_test.go
internal/configuration/provider_test.go
internal/configuration/test_resources/config.durations.yml

Large integers used with the duration common  syntax failed to parse if they exceeded the ability to fit into an int32.

fix(configuration): fail to parse large int duration

---

config.template.yml
docs/content/en/configuration/identity-providers/open-id-connect.md
docs/content/en/integration/openid-connect/introduction.md
internal/configuration/config.template.yml
internal/configuration/schema/identity_providers.go
internal/configuration/schema/keys.go
internal/configuration/validator/const.go
internal/configuration/validator/identity_providers.go
internal/configuration/validator/identity_providers_test.go
internal/handlers/handler_oidc_token_test.go
internal/handlers/handler_oidc_userinfo.go
internal/oidc/client.go
internal/oidc/client_auth.go
internal/oidc/client_test.go
internal/oidc/const.go
internal/oidc/const_test.go
internal/oidc/discovery.go
internal/oidc/errors.go
internal/oidc/keys.go
internal/oidc/keys_test.go
internal/oidc/provider.go
internal/oidc/provider_test.go
internal/oidc/store_test.go
internal/oidc/types.go
internal/oidc/types_test.go

This adds the authentication machinery for the client_secret_jwt Default Client Authentication Strategy.

feat(oidc): client secret jwt client auth

---

internal/authentication/file_user_provider.go
internal/authentication/file_user_provider_database_test.go
internal/authentication/file_user_provider_test.go

Add additional tests to the file provider.

test(authentication): file provider

---

config.template.yml
internal/configuration/config.template.yml

Further to #4222 comment most unnecessary configuration options.

docs: comment more unnecessary configuration options

---

docs/content/en/integration/proxies/nginx.md

docs: adjust nginx example for websockets

---

api/openapi.yml

docs(oidc): properly describe the introspection endpoint

---

docs/content/en/configuration/first-factor/introduction.md
docs/content/en/configuration/first-factor/ldap.md
docs/content/en/configuration/miscellaneous/ntp.md
docs/content/en/configuration/miscellaneous/server.md
docs/content/en/configuration/notifications/smtp.md
docs/content/en/configuration/prologue/common.md
docs/content/en/configuration/second-factor/webauthn.md
docs/content/en/configuration/security/regulation.md
docs/content/en/configuration/session/introduction.md
docs/content/en/configuration/session/redis.md
docs/content/en/configuration/storage/mysql.md
docs/content/en/configuration/storage/postgres.md
docs/content/en/configuration/telemetry/metrics.md
docs/layouts/shortcodes/confkey.html
docs/layouts/shortcodes/ref-common.html
internal/logging/const.go
internal/middlewares/authelia_context.go
internal/server/const.go
internal/server/handlers.go
internal/server/server.go

This is intended on clarifying some information regarding common configuration examples like buffers, timeouts, etc.

docs: clarification about common configurations

---

internal/handlers/handler_oidc_authorization_consent.go
internal/mocks/storage.go
internal/storage/provider.go
internal/storage/sql_provider.go
internal/storage/sql_provider_backend_postgres.go
internal/storage/sql_provider_queries.go

This fixes a state error during a PAR session were if the session requires consent the flow fails.

fix(oidc): par consent state error

---

docs/content/en/overview/security/measures.md
internal/middlewares/const.go
internal/middlewares/headers.go
internal/server/asset.go
internal/server/template.go
internal/suites/example/compose/nginx/portal/nginx.conf

This updates the default headers for many endpoints per the OWASP best practices.

feat(server): update default headers

---

docs/content/en/integration/openid-connect/introduction.md
internal/handlers/handler_oidc_authorization.go
internal/middlewares/util.go
internal/oidc/client_credentials.go
internal/oidc/client_credentials_test.go
internal/oidc/client_policy.go
internal/oidc/config.go
internal/oidc/const.go
internal/oidc/discovery.go
internal/oidc/flow_client_credentials.go
internal/oidc/flow_refresh.go
internal/oidc/resposne_mode.go
internal/oidc/types.go
internal/oidc/types_test.go
internal/oidc/util.go
internal/suites/example/compose/oidc-client/docker-compose.yml
internal/suites/scenario_oidc_test.go

This implements RFC9207 OAuth 2.0 Authorization Server Issuer Identification which is part of the FAPI 2.0 security profile.

feat(oidc): authz server issuer identification

---

internal/commands/context.go
internal/commands/root.go
internal/configuration/validator/const.go
internal/configuration/validator/log.go
internal/configuration/validator/log_test.go
internal/logging/const.go
internal/logging/logger.go

This logs user info at startup as a debug log message and additionally ensures the logger is configured much earlier for usage.

refactor(logging): log user at startup

---

cmd/authelia-gen/cmd_docs_data.go
cmd/authelia-gen/cmd_locales.go
docs/data/configkeys.json
docs/data/languages.json
docs/data/misc.json

This makes it easier to see adjustments to the docs data and spot errors.

docs: pretty format json data

---

internal/oidc/client_credentials.go
internal/oidc/handler_introspection.go

Instead of converting the secret to bytes then back to a secret type this allows us to use it directly.

refactor: use client secret directly

---

docs/content/en/integration/openid-connect/tailscale/index.md

I know I only changed one character, but every bit counts, right? :sweat_smile:

docs: markdown fix on tailscale

---

docs/content/en/configuration/miscellaneous/logging.md
internal/logging/logger.go
internal/logging/logger_test.go

This adds a date time layout option for the log file path.
Closes #6136

feat(logging): date time layout

---

docs/content/en/integration/proxies/swag.md

Update SWAG docs for upstream changes to `authelia-server.conf` template.

docs(swag): Update for upstream changes

---

docs/content/en/configuration/prologue/common.md
internal/configuration/schema/types_address.go
internal/configuration/schema/types_address_test.go
internal/configuration/validator/server.go
internal/configuration/validator/telemetry.go
internal/server/handlers.go
internal/server/server.go

Adds a subpath configuration query parameter to unix sockets and other listeners.

feat(configuration): unix socket listener subpath

---

docs/content/integration/openid-connect/homarr/index.md

This adds an integration doc for Homarr.

docs(oidc): add homarr integration

---

cmd/authelia-scripts/cmd/gen.go
docs/content/integration/openid-connect/homarr/index.md
docs/content/integration/openid-connect/nextcloud/index.md
docs/content/reference/cli/authelia/authelia_build-info.md
internal/commands/build-info.go
internal/commands/const.go
internal/suites/suite_cli_test.go

This fixes an issue where the build-info command is too verbose.

fix(commands): build-info too verbose

---

docs/content/integration/openid-connect/expressjs/index.md
docs/content/integration/openid-connect/wikijs/index.md

This adds a Wiki.js theoretical example based on their docs.

docs(oidc): wikijs example

---

examples/compose/lite/docker-compose.yml
examples/compose/local/docker-compose.yml
internal/suites/example/compose/traefik2/docker-compose.yml

This reverts commit 2d07d8dcd656e5d4cd23ec9db34160fa31cb5eb1.

revert update traefik docker tag to v3

---

internal/middlewares/cors.go
internal/middlewares/cors_test.go

The Cross-Origin Resource Sharing headers were included in responses when the request was not a proper request or a preflight. This fixes that issue.

fix(middlewares): cors responses without preflight

---

docs/content/configuration/identity-providers/openid-connect/clients.md
docs/content/configuration/miscellaneous/server.md
docs/content/integration/prologue/get-started.md
docs/content/integration/proxies/introduction.md
docs/content/roadmap/prologue/introduction.md
docs/layouts/shortcodes/confkey.html

This updates the styling of the reference alerts.

docs: use modern alert style for reference notes

---

internal/storage/sql_provider_queries.go

This fixes an issue where changing an encryption key for storage would fail.
Fixes #7611

fix(storage): change encryption key fails

---

docs/content/integration/openid-connect/incus/index.md

This adds Incus OpenID Connect integration docs.

docs(oidc): incus integration

---

cmd/authelia-scripts/cmd/build.go

Update to freebsd14 build toolchain via crossbuild container.

ci(cmd): build with freebsd14 toolchain

---

docs/content/integration/openid-connect/rocket-chat/index.md

This adds a rocket.chat integration.

docs(oidc): rocket.chat

---

docs/content/integration/openid-connect/matomo/index.md

This adds a matomo integration.

docs(oidc): matomo

---

web/src/views/Settings/TwoFactorAuthentication/CredentialItem.tsx

This fixes a UX bug where the webauthn credential buttons were crowded.

fix(web): webauthn buttons crowded

---

internal/suites/BypassAll/users.yml
internal/suites/CLI/users.yml
internal/suites/Caddy/users.yml
internal/suites/Docker/users.yml
internal/suites/DuoPush/users.yml
internal/suites/Envoy/users.yml
internal/suites/HAProxy/users.yml
internal/suites/MariaDB/users.yml
internal/suites/MultiCookieDomain/users.yml
internal/suites/MySQL/users.yml
internal/suites/NetworkACL/users.yml
internal/suites/OIDC/users.yml
internal/suites/OIDCTraefik/users.yml
internal/suites/OneFactorOnly/users.yml
internal/suites/PathPrefix/users.yml
internal/suites/Postgres/users.yml
internal/suites/ShortTimeouts/users.yml
internal/suites/Standalone/users.yml
internal/suites/Traefik/users.yml
internal/suites/TwoFactor/users.yml

This change ensures all user databases are consistent across the suites where utilised.

refactor(suites): remove commentary from suite based user databases

---

docs/content/integration/openid-connect/bookstack/index.md
docs/content/integration/openid-connect/budibase/index.md
docs/content/integration/openid-connect/cloudflare-zerotrust/index.md
docs/content/integration/openid-connect/gitlab/index.md
docs/content/integration/openid-connect/hedge-doc/index.md
docs/content/integration/openid-connect/homarr/index.md
docs/content/integration/openid-connect/jellyfin/index.md
docs/content/integration/openid-connect/mealie/index.md
docs/content/integration/openid-connect/nextcloud/index.md
docs/content/integration/openid-connect/outline/index.md
docs/content/integration/openid-connect/proxmox/index.md
docs/content/integration/openid-connect/seafile/index.md
docs/content/integration/openid-connect/synology-dsm/index.md

Hi,
fixed some more callouts with the unsupported link style. That should hopefully be all now.

docs: fix references in callouts

---

docs/content/integration/openid-connect/harbor/index.md

As discussed here https://github.com/authelia/authelia/discussions/8354

Update Harbor integration documentation page

---

docs/content/integration/deployment/docker.md
docs/content/reference/guides/templating.md
examples/compose/local/setup.sh
internal/configuration/provider_test.go
internal/configuration/test_resources/config_glob.yml
internal/configuration/test_resources/config_walk.yml
internal/configuration/test_resources/config_walk/general.yml
internal/configuration/test_resources/config_walk/server.yml
internal/templates/funcs.go
internal/templates/funcs_test.go
internal/templates/util.go

Adds the missing glob, walk, fromYaml, toYaml, toYamlPretty, and toYamlCustom functions; as well as several time based functions similar to the helm function equivalents.

fix(templates): add missing functions

---

internal/templates/funcs_test.go

This pr makes tests related to time conversion work for multiple timezones.
Should allow the tests to pass in any timezone.

test(templates): handle multiple timezones correctly

---

web/src/views/Settings/TwoFactorAuthentication/OneTimePasswordConfiguration.tsx
web/src/views/Settings/TwoFactorAuthentication/OneTimePasswordCredentialItem.tsx
web/src/views/Settings/TwoFactorAuthentication/OneTimePasswordInformationDialog.tsx
web/src/views/Settings/TwoFactorAuthentication/OneTimePasswordPanel.tsx
web/src/views/Settings/TwoFactorAuthentication/TwoFactorAuthenticationView.tsx

This fixes an undesirable default method UX where the default method for a browser is not correctly set when they register a new method.
Closes #8345

fix(web): undesirable default method ux

---

docs/content/blog/authelia-traefik-setup-guide/index.md

Summary:
- Prefer single quotes on all YAML string literals.
- Ensure markdown headings have single newlines surrounding them.
- Ensure all YAML comments are commented with two `##` followed by a space to symbolize they are not meant to be uncommented.
- Fix a minor config deprecation.

docs: update blog post

---

docs/content/integration/openid-connect/introduction.md
docs/content/integration/openid-connect/jellyfin/index.md
docs/content/integration/openid-connect/wordpress/index.md

No idea how I missed that before, but the extra `//` don't seem right.
Resolves: #8582 and #8549

docs: misc improvements

---

docs/content/integration/openid-connect/freshrss/index.md
docs/content/integration/openid-connect/linkwarden/index.md
docs/content/integration/openid-connect/wud/index.md

This adds two requested apps to our OpenID Connect 1.0 integration docs.

docs(oidc): add linkwarden and wud

---

docs/content/integration/openid-connect/hoarder/index.md

Add Hoarder integration guide
- [Hoarder OAuth OIDC config](https://docs.hoarder.app/configuration#authentication--signup)
- [Hoarder GitHub Dicussion Authelia Configuration](https://github.com/hoarder-app/hoarder/discussions/)

docs(oidc): add hoarder

---

internal/configuration/validator/session_test.go

This adds a test for IPv6 domains.

test(configuration): add test case for ipv6 domains

---

internal/notification/smtp_auth.go

This adjusts hte SMTP auth preferences to prefer better authentication methods.

refactor(notifier): smtp auth preference

---

config.template.yml
docs/content/configuration/identity-providers/openid-connect/provider.md
docs/static/schemas/v4.39/json-schema/configuration.json
internal/commands/context.go
internal/configuration/config.template.yml
internal/configuration/provider_test.go
internal/configuration/schema/identity_providers.go
internal/configuration/schema/keys.go
internal/configuration/validator/configuration.go
internal/configuration/validator/const.go
internal/configuration/validator/identity_providers.go
internal/configuration/validator/identity_providers_test.go
internal/mocks/user_provider.go
internal/oidc/client.go
internal/oidc/client_policy.go
internal/oidc/client_policy_test.go
internal/oidc/client_test.go
internal/oidc/discovery_test.go
internal/oidc/provider.go
internal/oidc/provider_test.go
internal/oidc/store.go
internal/oidc/store_test.go

This adds a network criteria to the Authorization Policies for OpenID Connect 1.0 clients.

feat(oidc): authorization policy network criteria

---

docs/content/integration/openid-connect/stirling-pdf/index.md

This is my first contribution of a new integration, could somebody check it? It is inspired by #8781

added stirling-pdf integration

---

docs/content/configuration/storage/mysql.md
docs/content/configuration/storage/postgres.md
internal/configuration/validator/const.go
internal/configuration/validator/storage.go
internal/configuration/validator/storage_test.go

This allows configuring peer authentication for PostgreSQL and MySQL/MariaDB servers.

feat(storage): peer authentication

---

docs/content/configuration/miscellaneous/server-endpoints-authz.md
docs/static/schemas/v4.39/json-schema/configuration.json
internal/authentication/cached.go
internal/authentication/cached_test.go
internal/configuration/schema/keys.go
internal/configuration/schema/server.go
internal/configuration/validator/const.go
internal/configuration/validator/server.go
internal/configuration/validator/server_test.go
internal/handlers/handler_authz_authn.go
internal/handlers/handler_authz_builder.go
internal/handlers/handler_authz_builder_test.go
internal/handlers/handler_authz_test.go

This adds the ability to cache successful basic authz attempts.

feat(handlers): basic authz caching

---

internal/configuration/test_resources/i18n/example1/locales/en/portal.json
internal/configuration/test_resources/i18n/example2/locales/en/portal.json
internal/configuration/validator/const.go
internal/configuration/validator/server.go
internal/configuration/validator/server_test.go
internal/server/asset.go
internal/server/server.go
internal/suites/Caddy/configuration.yml
internal/suites/Envoy/configuration.yml

This adjusts the assets validations to only validate the asset overrides.

test(i18n): validate i18n asset overrides

---

.buildkite/annotations/artifacts
.buildkite/deployment.sh
.buildkite/hooks/post-command
.buildkite/hooks/pre-artifact
.buildkite/hooks/pre-command
.buildkite/steps/ghartifacts.sh
Dockerfile
Dockerfile.coverage
Dockerfile.dev
cmd/authelia-scripts/cmd/build.go
cmd/authelia-scripts/cmd/const.go
cmd/authelia-scripts/cmd/helpers_docker.go
internal/suites/environment.go
internal/suites/suite_high_availability_test.go

This change builds based off of our own base libc image created from scratch, we are also now deprecating our musl builds.

feat: build from authelia/base base image

---

go.mod
go.sum
internal/configuration/validator/identity_providers.go
internal/oidc/config.go
internal/oidc/const.go
internal/oidc/errors.go
web/src/constants/SearchParams.ts
web/src/layouts/LoginLayout.tsx
web/src/views/ConsentPortal/CompletionView.tsx

This fixes an edge case where users were not redirected to the consent completion view.

fix(web): no redirection to completion view

---

go.mod
go.sum
internal/commands/debug.go
internal/handlers/handler_oauth2_oidc_userinfo.go
internal/middlewares/const.go

The UserInfo Endpoint had a cumbersome flow, and this addresses some of these issues. It also implements some practices from RFC6750.

refactor(handlers): userinfo cumbersome

---

docs/content/configuration/methods/files.md

This elaborates on the requirements for config path discovery.

docs(configuration): additional config paths info

---

.buildkite/pipeline.yml

This change aligns the hard-coded pipeline configuration with what is configured in Buildkite.

ci(buildkite): update hardcoded steps
