Dockerfile
docker-compose.yml
package.json

Exposes port 80 in the Dockerfile so that in can be used as a docker service by docker swarm

Expose port 80 in the Dockerfile

---

README.md
config.template.yml
example/nginx_conf/index.html
example/nginx_conf/nginx.conf
src/index.js
src/lib/identity_check.js
src/lib/routes/u2f.js
src/lib/routes/u2f_register.js
src/lib/server.js
src/public_html/js/login.js
src/public_html/js/totp-register.js
src/public_html/js/u2f-register.js
src/views/totp-register.ejs
test/unitary/test_data_persistence.js
test/unitary/test_server.js
test/unitary/test_server_config.js

Today, the user of the server is authenticating per subdomain. Indeed the session cookie has a limited scope (the subdomain). To allow real SSO accros subdomains, the session cookie must have a wider scope (the domain scope).
After the change, redirections have been reworked and the readme updated to ask the user to add lines to /etc/hosts to test authelia accross multiple domains.

Handle SSO accross subdomains

---

config.template.yml

Fortunately the discussion in issue #14 helped me figure this out.  Eventually... :-).
Could not get the buttons to register for TOTP or U2F.  Kept getting a message that "the email could not be sent" - which I thought indicated an issue with the file-based notification. 
Could get the notification.txt when doing a password change, so dug deeper.  Added and ran tcpdump on the authelia_auth instance, and was seeing the 403 error for all calls - and noticed the domain for the cookie...
Ran into two different issues while verifying this - I think credential may be cached so that log-out doesn't work, and saw some occasional odd connection problems with the ldap server.  But tested enough to determine that those do not seem related to this change.
Thanks, and Best Regards,
Paul

domain used for cookie - an issue in the example

---

example/nginx/nginx.conf
scripts/integration-tests.sh
src/client/lib/QueryParametersRetriever.ts
src/client/lib/firstfactor/index.ts
src/client/lib/secondfactor/index.ts
src/server/lib/routes/firstfactor/post.ts
src/server/lib/routes/secondfactor/redirect.ts
src/server/lib/routes/verify/get.ts
test/features/authentication.feature
test/features/redirection.feature
test/features/resilience.feature
test/features/support/world.ts
test/unit/server/routes/firstfactor/post.test.ts

Before this fix, the redirection URL was stored in the user session,
but this has a big drawback since user could open several pages in
browser and thus override the redirection URL leading the user to
be incorrectly redirected.

Add redirection URL as a query parameter during authentication

---

example/nginx/nginx.conf

It seems nginx is closing the connection for some backends if
`proxy_set_header Content-Length "";` is not added to the
verification endpoint.

Add Content-Length header to the forwarded request to Authelia

---

config.template.yml
config.test.yml
server/src/lib/ServerVariablesHandler.ts
server/src/lib/configuration/ConfigurationAdapter.ts
server/src/lib/ldap/Authenticator.ts
server/src/lib/ldap/Client.ts
server/src/lib/ldap/ClientFactory.ts
server/src/lib/ldap/EmailsAndGroupsRetriever.ts
server/src/lib/ldap/GroupsRetriever.ts
server/src/lib/ldap/IClient.ts
server/src/lib/ldap/IEmailsRetriever.ts
server/src/lib/ldap/IGroupsRetriever.ts
server/src/lib/ldap/ILdapClient.ts
server/src/lib/ldap/ILdapClientFactory.ts
server/src/lib/ldap/LdapClient.ts
server/src/lib/ldap/LdapClientFactory.ts
server/test/configuration/LdapConfigurationAdaptation.test.ts
server/test/ldap/Authenticator.test.ts
server/test/ldap/Client.test.ts
server/test/ldap/GroupsRetriever.test.ts
server/test/mocks/ldap/ClientStub.ts
server/test/mocks/ldap/LdapClientFactoryStub.ts
server/test/mocks/ldap/LdapClientStub.ts
test/features/authentication.feature

Previously, string "{0}" was replaced by the user dn in the groups_filter
attributes of the LDAP configuration.
However, if the groups children only have a memberUid attribute, one would
like to use the username instead of the user dn.
Since the user dn can be built from the username, "{0}" is now replaced
by the username instead of the user dn so that an LDAP relying on attribute
'memberUid' can be used.

Use username matcher instead of user dn in group filter

---

server/src/lib/configuration/ConfigurationAdapter.ts
server/src/lib/configuration/adapters/ACLAdapter.ts
server/test/access_control/AccessController.test.ts
server/test/configuration/ConfigurationAdapter.test.ts
server/test/configuration/adapters/ACLAdapter.test.ts
test/features/redirection.feature
test/features/regulation.feature
test/features/step_definitions/authentication.ts
test/features/step_definitions/notifications.ts

Basically, the ACL configuration was very static and it was not allowed
to remove 'any', 'groups', 'users'. The application crashed when those
keys did not exist.
After this fix, every key is optional and replaced by a default value
for the app configuration to be complete and used by Authelia.
Later, a configuration validator will be implemented to detect issues
with configuration at startup.

Adapt ACL configuration to make it more flexible

---

scripts/docker-publish.sh

Prior to this fix, every master commits was released to Dockerhub under latest
tag and tagged commit was released with a version tag in Dockerhub.
'Latest' tag in dockerhub should reference the latest released version and not
the head of master branch.
Thus, after this fix, 'latest' tag references the latest released version of
Authelia and 'master' tag references the head of master git branch.

Deploy latest along with release tag

---

server/src/lib/Server.ts
server/src/lib/ldap/Client.ts
server/src/lib/ldap/ClientFactory.ts
server/src/lib/ldap/InputsSanitizer.ts
server/src/lib/ldap/SanitizedClient.ts
server/test/ldap/InputsSanitizer.test.ts
server/test/ldap/SanitizedClient.test.ts

Note: nothing has been done for passwords. They should be sanitized by dovehash (to be checked)

Add input sanitizer to LDAP client to protect against LDAP injections

---

config.template.yml
config.test.yml
server/src/lib/configuration/ConfigurationParser.ts
server/src/lib/ldap/Client.ts
server/src/lib/routes/verify/get.ts
server/test/configuration/LdapConfigurationAdaptation.test.ts
server/test/ldap/Client.test.ts

Sometimes, LDAP organization is such that groups membership cannot be computed
with username only. User DN is required to retrieve groups.
e.g. user Joe has a username joe and a cn of Joe Blogs, resulting in a dn of
cn=Joe Blogs,ou=users,dc=example,dc=com which is needed to retrieve groups
but cannot be computed from joe only.
Issue was reported in issue #146

Add {dn} as an available matcher in LDAP groups filter

---

Dockerfile
docker-compose.dev.yml
example/ldap/access.rules
example/ldap/base.ldif
package.json
server/src/index.ts
server/src/lib/IdentityCheckMiddleware.ts
server/src/lib/ServerVariablesInitializer.ts
server/src/lib/ldap/Client.ts
server/src/lib/ldap/ClientFactory.ts
server/src/lib/utils/HashGenerator.ts
server/test/ServerConfiguration.test.ts
server/test/SessionConfigurationBuilder.test.ts
server/test/ldap/Client.test.ts
server/test/ldap/PasswordUpdater.test.ts
server/test/server/PrivatePages.ts
server/test/server/PublicPages.ts
server/test/utils/HashGenerator.test.ts
server/types/Dependencies.ts

Uses the crypt() function to do password encryption. This function handles
several schemes such as: MD5, Blowfish, SHA1, SHA2.
SHA-512 is used in Authelia for best security.
The algorithm is fully described in
https://www.akkadia.org/drepper/SHA-crypt.txt
The 'crypt3' npm package has been added as a dependency to use the crypt()
function. The package needs to be compiled in order to call the c function,
that's why python, make and C++ compiler are installed temporarily in the
Docker image.

Strengthen password in LDAP using SHA512 crypt algorithm

---

config.template.yml
config.test.yml
server/src/lib/Server.ts
server/src/lib/configuration/Configuration.d.ts
server/src/lib/configuration/Validator.ts
server/src/lib/notifiers/EMailNotifier.ts
server/src/lib/notifiers/IMailSenderBuilder.ts
server/src/lib/notifiers/MailSenderBuilder.ts
server/src/lib/notifiers/NotifierFactory.ts
server/test/ServerConfiguration.test.ts
server/test/configuration/ConfigurationParser.test.ts
server/test/configuration/LdapConfigurationAdaptation.test.ts
server/test/configuration/Validator.test.ts
server/test/mocks/notifiers/MailSenderBuilderStub.ts
server/test/notifiers/EMailNotifier.test.ts
server/test/notifiers/MailSenderBuilder.test.ts
server/test/notifiers/NotifierFactory.test.ts
server/test/server/PrivatePages.ts
server/test/server/PublicPages.ts

Replaces the static gmail handler with a more generic one using NodeMailer's well know services[1]. 
https://nodemailer.com/smtp/well-known/

Less restrictive email handler - replace gmail with generic

---

example/nginx/nginx.conf
server/src/lib/ErrorReplies.ts
server/src/lib/IdentityCheckMiddleware.ts
server/src/lib/routes/error/401/get.ts
server/src/lib/routes/error/403/get.ts
server/src/lib/routes/error/redirector.ts
server/src/lib/web_server/RestApi.ts
server/src/views/errors/401.pug
server/src/views/errors/403.pug
server/test/IdentityCheckMiddleware.test.ts
server/test/mocks/express.ts
server/test/routes/errors/401/get.test.ts
server/test/routes/errors/403/get.test.ts
server/test/routes/firstfactor/post.test.ts
server/test/routes/password-reset/identity/PasswordResetHandler.test.ts
server/test/routes/password-reset/post.test.ts
server/test/routes/secondfactor/totp/sign/post.test.ts
server/test/routes/secondfactor/u2f/register/post.test.ts
server/test/routes/secondfactor/u2f/register_request/get.test.ts
server/test/routes/secondfactor/u2f/sign/post.test.ts
server/test/routes/secondfactor/u2f/sign_request/get.test.ts
server/test/routes/verify/get.test.ts
shared/api.ts
test/features/redirection.feature
test/features/restrictions.feature

From this commit on, api endpoints reply with a 401 error code and non api
endpoints redirect to /error/40X.
This commit also fixes missing restrictions on /loggedin (the "already logged
in page). This was not a security issue, though.
The change also makes error pages automatically redirect the user after few
seconds based on the referrer or the default_redirection_url if provided in the
configuration.
**Warning:** The old /verify endpoint of the REST API has moved to /api/verify.
You will need to update your nginx configuration to take this change into
account.

Fix endpoints redirection on errors

---

.travis.yml
README.md
doc/api_data.js
doc/api_data.json
doc/api_project.js
doc/api_project.json
example/nginx/portal/nginx.conf
server/src/lib/ErrorReplies.ts
server/src/lib/routes/verify/get.ts
server/test/routes/verify/get.test.ts
shared/api.ts
test/features/authelia.feature
test/features/step_definitions/authelia.ts

Traefik handles auth forwarding but does not manage redirections like Nginx.
Therefore, Authelia must redirect the user and Traefik will forward this
request.
To support both Nginx and Traefik, /api/verify is now configurable with the
'redirect' get parameter. If the verification fails and 'redirect' is not
provided the response will be a 401 error as before.
If the parameter is provided and set to any URL, the response will be a
redirection (302) to this URL.

Support 'redirect' parameter in /api/verify endpoint to support Traefik

---

client/src/css/01-main.css
server/src/views/firstfactor.pug
server/src/views/password-reset-form.pug
server/src/views/password-reset-request.pug
server/src/views/secondfactor.pug

Currently notifications reflow the document which causes the interface
to jump twice which can be frustrating if you're trying to click
something.
This change makes the notification appear at the top of the form as
such:
@clems4ever do you agree with this? If not feel free to discard this PR.

Make notifications appear on top instead of inline

---

config.minimal.yml
docker-compose.swarm.minimal.yml

I changed the current minimal config to include all configuration snippets that are needed for a working config, since there were some things missing that needed to be taken from other configs.
I also added an example configuration that is working with docker swarm. A reverse proxy would still need to be configured, but I dont currently have a 100% working configuration with traefik internal tools, which is why I left out my current one.

Changed minimal config to provide for a working installation + docker swarm example

---

config.template.yml
example/kube/authelia/configs/config.yml
server/src/lib/authentication/backends/ldap/Session.spec.ts
server/src/lib/authentication/backends/ldap/Session.ts

On some LDAP servers, the `uid` attribute is more like a guid, while the
username exists instead in a dedicated field, like `username`. This
means the `uid` is not necessarily equal to `username`.
This is allows referencing using the `uid` to search for groups in the same
way as `dn` so that one can explicitly match the `memberuid` to the `uid` for
the user without the assumptions that come with using `{0}`.
I have run unit tests, but need to verify integration tests pass as well.
This is also my first time working with TypeScript, so let me know if anything I've done is weird. I'm happy to make updates.

Add ability to search for groups using {uid}

---

server/src/lib/routes/secondfactor/duo-push/Post.spec.ts
server/src/lib/routes/secondfactor/duo-push/Post.ts

This change provides additional details in the Duo 2FA request including:
- Client IP
- Target URL

Capture IP address and Target URL in Duo 2FA request

---

server/src/lib/routes/verify/GetSessionCookie.ts

This change includes attaching the following headers when an authenticated session exists while using the bypass strategy:
- Remote-User
- Remote-Groups

Fix attaching User/Groups headers for bypass strategy

---

.dockerignore
.gitignore
server/src/lib/AuthenticationSessionHandler.ts
server/src/lib/BelongToDomain.ts
server/src/lib/Server.ts
server/src/lib/routes/firstfactor/post.ts
server/src/lib/routes/verify/Get.ts

This adds the following major features:
- The ability to have passwords passed in via environment variables rather than the configuration file
This feature is needed to allow the use of Kubernetes secrets when deploying Authelia in Kubernetes via a Docker image
This adds the following minor features:
- Better debugging output for domain/subdomain comparison
- additions to .gitignore for vim and idea editors
- A .dockerignore file to make the copy of the initial context to the docker daemon go faster
These features were necessary to increase developer productivity and make it simpler to track down domain/cookie issues.

Allow passwords to be specified via environment

---

Dockerfile
client/package-lock.json
package-lock.json
server/src/lib/ServerVariablesInitializer.ts
server/src/lib/authentication/backends/ldap/SessionFactory.ts
server/src/lib/authentication/backends/ldap/connector/Connector.ts
server/src/lib/authentication/backends/ldap/connector/ConnectorFactory.ts
server/src/lib/configuration/schema/LdapConfiguration.ts

What this pull request does:
* Provides users the ability to specify the CA of their ldaps server when such server uses a private CA.
* Added some info and debug logging to understand how Authelia initializes the TLS system in ldapjs
Why do we need it:
* Not all ldaps servers will use a certificate signed by a publicly trusted CA. For example: in corporate environments with an existing authentication stack, or in a Kubernetes environment where the ldaps server uses a certificate signed by the cluster CA
* The logging makes it easier to track what is going on when setting up an ldaps backend.
Risks:
The version of Node was moved from the 8.x branch to the 10.x branch which uses an improved TLS stack. The resulting Docker image has been tested in:
* ldaps with publicly trusted CA (which was …

Add Support for Private Certificate Authority Signed LDAPS Server Certificates

---

Dockerfile
docs/deployment-production.md

This change provides the ability to specify a [timezone](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) with the `TZ` variable, e.g: `TZ=America/New_York` this will allow end users to select what the "correct" date/time is for their docker instance of Authelia.

Add ability to set timezone for Docker container

---

docs/deployment-dev.md

Lost a couple hours to this subtle detail of the `users_database.yml` format. I was missing the `{CRYPT}` at the beginning of the hashed password line. 
Alternatively, the `hash-password` tool could prepend this automatically, but I'm pretty new to Authelia, and so I thought a README edit was better first PR 😜

Add "{CRYPT}" detail to deployment-dev

---

.gitignore
.travis.yml
Dockerfile.arm32v7
Dockerfile.arm64v8
cmd/authelia-scripts/cmd_bootstrap.go
cmd/authelia-scripts/cmd_ci.go
cmd/authelia-scripts/cmd_docker.go
cmd/authelia-scripts/docker.go
cmd/authelia-scripts/main.go

This change provides Authelia builds for the following architectures:
- amd64
- arm32v7
- arm64v8
The arm32 variant has been tested as I own the respective hardware, I'd recommend you test the arm64 variant with your hardware @clems4ever. It's also available at `nightah/authelia` just pull the latest tag to ensure the manifests work too.

Enable Multiarch docker builds

---

cmd/authelia-scripts/cmd_docker.go
cmd/authelia-scripts/docker.go

Per the title, this utilises Docker's v2 REST API to remove tags that have been published into a manifest.

Remove unnecessary tags from DockerHub after publishing a manifest

---

cmd/authelia-scripts/docker.go

As per the description, during the publishing phase if the curl to remove tags or publish the README fails due to a transient error this will not result in the intended outcome, the change treats non-200 responses as a failure and will retry up to three times.

[Docker] Treat non-200 responses as an error and retry up to 3 times

---

cmd/authelia-scripts/docker.go

This should prevent the `README.md` not being pushed and tags sometimes not cleaning up.

Retry curl up to 3 times for transient network errors

---

cmd/authelia-scripts/cmd_docker.go

To standardise the logging in the helper and so they show up in Travis.
Though this points to another issue that something is wrong with `log.Debug` which also needs to be investigated.

Adjust logging for Docker helper script

---

CHANGELOG.md
Dockerfile
Dockerfile.arm32v7
Dockerfile.arm64v8
README.md
bootstrap.sh
cmd/authelia-scripts/cmd_docker.go
cmd/authelia-scripts/cmd_serve.go
cmd/authelia-scripts/docker.go
cmd/authelia/constants.go
cmd/authelia/main.go
docs/configuration.md
docs/deployment-dev.md
docs/deployment-production.md
example/compose/authelia/docker-compose.backend.yml
example/compose/authelia/resources/entrypoint.sh
example/compose/authelia/resources/run.sh
internal/configuration/validator/authentication.go
internal/configuration/validator/authentication_test.go

In order to easily check where a given binary comes from, we embed information about the commit hash and the release tag in the binary.
Also add a configuration check for missing enclosing parenthesis in LDAP filters.

Embed commit hash and tag in Authelia binary.

---

internal/middlewares/authelia_context.go
internal/middlewares/authelia_context_test.go

Authelia needs to know with what IP was the request originating in
order to apply network based ACL rules. Authelia already supported
X-Forwarded-For but X-Real-IP is another way to define it. It takes
precedence over X-Forwarded-For.

Read X-Real-Ip as the remote IP provided by the proxy.

---

internal/authentication/ldap_user_provider.go

- Make the DN concatenation uniform between both Users and Groups
- Make it possible to use a blank or commented out additional_users_dn or additional_groups_dn for ldap backends
- Fixes #508

Allow blank additional_groups_dn and additional_users_dn

---

internal/configuration/schema/notifier.go
internal/notification/smtp_login_auth.go
internal/notification/smtp_notifier.go

- If the StartTLS extension is advertised we automatically StartTLS
- Uses the secure config key to determine if we should verify the cert
- Attempt auth when the config has a SMTP password and the server supports the AUTH extension
- Check the mechanisms supported by the server and use PLAIN, LOGIN, or CRAM-MD5 depending on which is supported
- Changed secure key to use boolean values instead of strings
- Arranged SMTP notifier properties/vars to be in the same order
Fixes #464 
I've built and published an image on docker hub: [jamesdelliott/authelia:smtp-adaptive-auth](https://hub.docker.com/layers/jamesdelliott/authelia/smtp-adaptive-auth/images/sha256-d07bc0e6a4068d398f9d2b8d905d251fe062a07d4fd244cf857a180fb3bfd4d0)
Requires Testing:
Things I plan to add to this PR:
Tests unrelated to …

Implement SMTP StartTLS and Adaptive Auth

---

.buildkite/steps/e2etests.sh

Default parameters retry on exit_status=* and a single step is retried a maximum of 2 times (3 total runs including initial failure)

Automatically retry failed Buildkite integration tests

---

.buildkite/pipeline.yml

This is so they do not appear on the Buildkite interface when their subsequent steps will not be executed.

Make Buildkite wait blocks conditional

---

.travis.yml

These steps should only run on the master or tagged branches.
This change also means that while we are utilising Travis that there aren't long 20-30 minute blocks waiting on a PR to go green due to the build steps.

Optimise Travis build and deploy steps

---

.buildkite/pipeline.yml
Dockerfile
Dockerfile.arm32v7
Dockerfile.arm64v8

@clems4ever: I don't believe there's an actual requirement to have a Debian based container now that this the binary is truly static.
If there was another reason behind the Debian based container, let me know as I still have https://github.com/authelia/authelia/tree/docker-debian-variant sitting around.
Closes #496

Build static Go binary

---

Dockerfile
Dockerfile.arm32v7
Dockerfile.arm64v8

Reduce reliance on QEMU in order to speed up the pipeline.
Initial tests with a system under full load shows about 2-3x faster build stages, which was our single longest step.

Cross compile Go binary natively from amd64

---

BREAKING.md
docs/proxies/nginx.md

In commit 9ae2096, the redirection parameter is changed in the example `nginx.conf`, and also in other places like `internal/middlewares/identity_verification.go`:
```
- link := fmt.Sprintf("%s://%s/#%s?token=%s", ctx.XForwardedProto(),
+ link := fmt.Sprintf("%s://%s%s?token=%s", ctx.XForwardedProto(),
```

Reflect change of 9ae2096 on the redirection param

---

.buildkite/pipeline.yml
internal/handlers/handler_firstfactor.go
internal/handlers/handler_firstfactor_test.go
internal/handlers/handler_verify.go
internal/handlers/handler_verify_test.go
internal/middlewares/authelia_context.go
internal/middlewares/types.go
internal/session/provider_test.go
internal/suites/scenario_inactivity_test.go
internal/suites/webdriver.go

This must be merged prior to https://github.com/authelia/authelia/pull/554 to fix the tests.
This PR uses keep me logged boolean stored in the user session instead of relying on the expiration value stored in the cookie. That way we will be able to set an expiration to 1 year instead of 0.
This PR also removes user session caching in AutheliaCtx to make sure that user session is correctly wiped when inactivity timeout is reached.

Use keep me logged in bool

---

internal/handlers/handler_firstfactor.go

Adjust the remember me duration to 1 year. Was originally set to 0 which expires at the end of the user agents session. Usually this is when the browser is closed, tab is closed.
This functionality can still likely be reached by not selecting remember me, and having the expiration set to 0.
The behavior after this commit will be as follows (tested by me):
Remember Me unchecked: duration set as expiration config.
Remember me checked: duration set to 1 year.

Fixes Remember Me functionality

---

internal/handlers/handler_verify.go
internal/handlers/handler_verify_test.go
internal/suites/action_visit.go
internal/suites/scenario_redirection_url_test.go
internal/suites/suite_kubernetes_test.go
internal/suites/suite_standalone_test.go
internal/suites/suite_traefik_test.go
web/src/views/LoginPortal/LoginPortal.tsx

URL encoding that parameter solves PR #476.
Some URL parameters set during redirection were magically disappearing
after the redirection due to the authentication process. By using URL encoding,
those parameters should not be stripped anymore.

Encode URL set to rd parameter.

---

internal/authentication/ldap_user_provider.go
internal/authentication/ldap_user_provider_test.go

https://owasp.org/www-project-cheat-sheets/cheatsheets/LDAP_Injection_Prevention_Cheat_Sheet.html

Escape special LDAP characters as suggested by OWASP.

---

internal/regulation/regulator.go
internal/regulation/regulator_test.go

- Only set regulator to enabled if max_retries is not set to 0, default is false (zero value). See 
https://tour.golang.org/basics/12.
- Added test for the scenario.
- Fixes #584
I have PR's #588 and #589 open, and will rebase & force push which ever one is not merged first (and this is to be expected behaviour from me unless you have an alternate preference).

[FIX] Disable regulation when max_retries set to 0 (#584)

---

internal/notification/smtp_notifier.go

- Only attempt to close the connection once it's established.
- Defer the client Quit/Close so that it always executes at the end.
Draft: I'm still a bit concerned that this may have issues if the socket is broken during execution. This should only occur in very rare instances when there is a network interruption or if the SMTP server is not configured correctly. So I'm leaving it as a draft for now.
This relates to #585. What was happening is the connection completely failed to initialize, and we were trying to close a connection that was not opened at all. This is my fault.
Note: When this is ready I'll amend my commit with a fixes note (I completely forgot doing this too early can make an issue look utterly horrible). I'll also mark it ready to merge.

[FIX] SMTP Notifier Unhandled Error Conditions

---

.buildkite/hooks/post-command
.github/probot.js

This also removes the Buildkite trigger for commentary.
@clems4ever we need to do a couple things before this is merged.

[MISC] Utilise Probot for PR commentary

---

internal/handlers/handler_verify.go
internal/handlers/handler_verify_test.go

Many times users request help on misconfiguration issues due to http/https or because they visit a domain that is not under the protected domain defined in Authelia configuration.
Those logs gives information about the issue to help users know why authentication doesn't not work in those cases.

[MISC] Add several logs to help users detect misconfiguration issues

---

.buildkite/steps/aurhelper.sh

Need to fetch all tags prior to extracting the correct version.

[Buildkite] Fix AUR version tagging

---

internal/suites/example/compose/authelia/Dockerfile.backend
internal/suites/example/compose/authelia/docker-compose.backend.dev.yml
internal/suites/example/compose/authelia/docker-compose.frontend.dev.yml

Suites cannot be run locally anymore following the move of the example
directory into the suites directory.

[BUGFIX] Fix development workflow.

---

internal/authentication/ldap_user_provider.go
internal/authentication/ldap_user_provider_test.go

Also:
* change the log level of LDAP connection creation from debug to trace.
Fixes https://github.com/authelia/authelia/issues/647

[BUGFIX] Fix crash when no emails or groups are retrieved from LDAP.

---

config.template.yml
internal/configuration/schema/session.go
internal/session/provider_config.go
internal/session/provider_config_test.go

- Allow users to specify the DB number
- This is so users who use their redis for multiple purposes can have clear demarcation between their data
This is a simple change, works as expected. I haven't updated docs since we're moving to GitHub Pages but will look to make a commit there too. I added to unit tests as you'll see to verify the behavior of both no configuration and a value other than zero.

[FEATURE] Redis DB Index Selection

---

.buildkite/deployment.yml

* Update all dependencies to allow more parallel jobs.
* Remove concurrency limit for non-master deployments to prevent pipeline blocking.

[Buildkite] Optimise deployment dependencies

---

internal/handlers/handler_sign_duo.go
internal/handlers/handler_sign_duo_test.go
internal/handlers/handler_sign_totp.go
internal/handlers/handler_sign_totp_test.go
internal/handlers/handler_sign_u2f_step2.go
internal/handlers/handler_sign_u2f_step2_test.go

Session fixation attacks were prevented because a session ID was
regenerated at each first factor authentication but this commit
generalize session regeneration from first to second factor too.
Fixes #180

[FEATURE] Regenerate session IDs after 2FA authentication.

---

Dockerfile.arm32v7
Dockerfile.arm64v8

Built using `musl-1.1.24`, `linux-headers-headers-4.19.88`

[Buildkite] Update musl-cross-make toolchain to gcc 9.2.0

---

.buildkite/deployment.sh
.github/probot.js

This change will continue to perform unit and integration testing, however, disables deployment steps in association with dependabot PRs.
Deployment comments on the PR with autheliabot are also disabled.

[Buildkite] Fix pipeline to work alongside dependabot

---

BREAKING.md
config.template.yml
docs/configuration/authentication/ldap.md
internal/authentication/file_user_provider.go
internal/authentication/file_user_provider_test.go
internal/authentication/ldap_user_provider.go
internal/authentication/ldap_user_provider_test.go
internal/authentication/types.go
internal/configuration/schema/authentication.go
internal/configuration/test_resources/config.yml
internal/configuration/validator/authentication.go
internal/configuration/validator/authentication_test.go
internal/handlers/handler_firstfactor.go
internal/handlers/handler_firstfactor_test.go
internal/suites/HighAvailability/configuration.yml
internal/suites/LDAP/configuration.yml
internal/suites/example/compose/ldap/docker-compose.yml
internal/suites/example/compose/ldap/ldif/base.ldif
internal/suites/example/kube/authelia/configs/configuration.yml
internal/suites/example/kube/ldap/base.ldif
internal/suites/suite_high_availability.go
internal/suites/suite_ldap.go

In some setups, binding is case insensitive but Authelia is case
sensitive and therefore need the actual username as stored in the
authentication backend in order for Authelia to work correctly.

[BUGFIX] Set username retrieved from authentication backend in session.

---

internal/configuration/validator/authentication.go
internal/configuration/validator/authentication_test.go

This PR aligns the situation with what is currently documented.

[BUGFIX] Make users_filter configuration of LDAP backend optional.

---

internal/authentication/ldap_user_provider.go
internal/suites/example/compose/ldap/ldif/base.ldif

This aligns the search filter escaping to [RFC4515](https://tools.ietf.org/search/rfc4515).
I've also updated our `base.ldif` to be a closer match to RFC 2307.
Fixes #702.

[BUGFIX] LDAP group retrieval of users with parenthesis in their name

---

.buildkite/deployment.sh
.buildkite/pipeline.sh

If origin/master diverges beyond the initial fork-point on branches or external forks, the `git merge-base` command exits unsuccessfully. This will cause commits to incorrectly be recognised as a docs bypass. This change will catch the unsuccessful exit and treat it as a normal CI/CD run.
Examples:
- https://buildkite.com/authelia/authelia/builds/932
- https://buildkite.com/authelia/authelia/builds/933
- https://buildkite.com/authelia/authelia/builds/941

[Buildkite] Fix docs bypass for origin/master divergences

---

.buildkite/pipeline.sh

Ensure Unit and Integration testing is bypassed for tagged builds.
Similar to #756 this is to also catch tagged releases.

[Buildkite] Optimise pipeline for tagged deployments

---

internal/suites/example/compose/authelia/docker-compose.frontend.dev.yml

The latest react-scripts bumps broke the startup of the authelia-frontend
container because the new version of react-scripts behaves differently when
the container is spawned with a pseudo-tty and when there is not.

[MISC] Fix authelia-frontend dev server startup.

---

.buildkite/pipeline.sh

Fixes the regression #766 introduced as when the `build.branch` is `master` `build.tag` is `""`.

[Buildkite] Fix pipeline regression for master deployments

---

internal/suites/example/compose/nginx/portal/nginx.conf
internal/suites/example/compose/nginx/portal/nginx.https.conf

While working with suites in development, when home.example.com was visited for instance, the browser sometimes ended up displaying an error while the developer was expected to see the home page served over https.
This change configures an automatic redirection from http to https.

[MISC] Automatically redirect from http to https in suites.

---

internal/handlers/handler_verify.go

This enhancement clarifies the log message following discussion in
Fix #691

[MISC] Debug message shows used headers instead of fallback warning.

---

README.md
compose/lite/configuration.yml
compose/lite/docker-compose.yml
compose/lite/users_database.yml
compose/local/configuration.yml
compose/local/docker-compose.yml
compose/local/setup.sh
compose/local/traefik/certificates.yml
compose/local/users_database.yml
docs/configuration/storage/mysql.md
docs/configuration/storage/postgres.md
docs/contributing/index.md
docs/deployment/deployment-ha.md
docs/deployment/deployment-lite.md
docs/deployment/supported-proxies/traefik1.x.md
docs/deployment/supported-proxies/traefik2.x.md
docs/getting-started.md

This provides two flavours of compose bundles for users to test Authelia.
- Local
This bundle is intended for scenarios where the server will not be exposed to the internet, domains will be defined in the local hosts file and self-signed certificates will be utilised.
This bundle includes a script to generate all the required configuration and is intended as the quickest method to demo Authelia.
- Lite
This bundle is intended for scenarios where the server will be exposed to the internet, domains and DNS will need to be setup accordingly and certificates will be generated through LetsEncrypt.
The Lite element refers to minimal external dependencies; File based user storage, SQLite based configuration storage. In this configuration, the service will not scale well.
A future PR will also …

[Docker] Include docker-compose.yml examples to run Authelia

---

config.template.yml
internal/configuration/schema/validator.go
internal/configuration/validator/session.go
internal/configuration/validator/session_test.go
internal/session/encrypting_serializer.go
internal/session/encrypting_serializer_test.go
internal/session/provider_config.go
internal/session/provider_config_test.go
internal/utils/aes.go

This is a regression from v3. With this change session data is
encrypted with AES-GCM using a 256-bit key derived from the provided
secret.
Fix #652

[MISC] Encrypt session data in redis store.

---

web/package.json

It seems that running unit tests can result in failures if the build is not run on a clean machine, examples of this can be found at:
- https://buildkite.com/authelia/authelia/builds/1083#8916f6fc-6a53-4619-8c2e-a762f78f1de2
- https://buildkite.com/authelia/authelia/builds/1095#2206e39c-55dd-4311-8348-09f4f7c90fa1
This seems to be a pretty common issue too, just google issues with jest cache:
- https://github.com/vuejs/vue-jest/issues/56

[Buildkite] Disable jest cache due to erratic unit test behaviour

---

.buildkite/hooks/pre-exit

This is to optimise build times at the sacrifice of disk space/manual clean up tasks.

[Buildkite] Control clean builds with agent metadata

---

compose/lite/docker-compose.yml

docker-compose up -d no longer complains about the public service because of wrong indentation

[BUGFIX] Fix indenting on lite compose bundle

---

compose/lite/docker-compose.yml
compose/local/docker-compose.yml
docs/deployment/supported-proxies/traefik1.x.md
docs/deployment/supported-proxies/traefik2.x.md
internal/suites/example/compose/nginx/backend/docker-compose.yml

This is a follow up to resolve #842.

[DOCS] Add Remote-User and Remote-Groups headers to Traefik docs

---

internal/server/server.go
internal/suites/example/compose/haproxy/Dockerfile

This is to natively support the upstream HAProxy module haproxy-auth-request without patching.

[MISC] Allow HEAD method on /api/verify

---

config.template.yml
docs/configuration/authentication/file.md
internal/authentication/file_user_provider.go
internal/authentication/file_user_provider_test.go
internal/authentication/password_hash_test.go
internal/commands/hash.go
internal/configuration/schema/authentication.go
internal/configuration/validator/authentication.go
internal/configuration/validator/authentication_test.go
internal/handlers/const.go

* fix the schema mapping the YAML to the password hashing configuration
* add a nolint for gosec 'possibly hardcoded password' that was incorrect
Fixes #845

[BUGFIX] Password hashing schema map mismatch with docs

---

docs/configuration/miscellaneous.md
go.mod
go.sum
internal/server/server.go

* enabled only with trace logging
* allows go tool pprof usage when enabled
* enables both the expvarhandler and pprofhandler from fasthttp
* simplify tls/non-tls listen and serve
* make it easy to define custom settings of the fasthttp server in the future

[MISC] Add http debug routes

---

internal/suites/example/compose/authelia/docker-compose.frontend.dev.yml
internal/suites/example/compose/authelia/resources/reflex.conf

#767 added an interactive tty to the authelia-frontend server due toe a bump in react-scripts, this in turn consumes all logging and pages on a failure and made it difficult to interact with within the dev workflow.
The tty has been replaced with an open stdin as this also satisfies the react-scripts requirement.
This change also ignores the web directory in the reflex script to avoid errors and long start-ups in the authelia-frontend container.

[MISC] Fix authelia-{backend,frontend} dev server logging and startup

---

web/src/views/LoginPortal/FirstFactor/FirstFactorForm.tsx

Currently the first factor login page has somewhat inconsistent behaviour when pressing enter on a field.
The typical workflow will focus the next field from username -> password -> attempt login.
However if a user wants to tab down and hit spacebar to activate the remember me option, they cannot just hit enter and attempt a login.
This change will attempt a sign-in if the username and password fields both contain data and enter is pressed on either the username, password or remember me fields.
If the first condition is not met the the respective field(s) will error (turn red) and focus will be set to said field in sequential order per the normal workflow.

[MISC] Tweak frontend portal behaviour on enter keypress

---

internal/handlers/response.go

* prevents requirement to always 2FA if the user doesn't have permission to access a target URL
Fixes #816

[BUGFIX] 2FA after 1FA only when necessary for access to target

---

Dockerfile
Dockerfile.arm32v7
Dockerfile.arm64v8
Dockerfile.darwin
cmd/authelia-scripts/cmd_build.go
internal/server/index.go
internal/server/server.go
internal/suites/example/compose/authelia/docker-compose.backend.dev.yml
internal/suites/example/compose/authelia/resources/entrypoint-backend.sh
internal/suites/example/compose/authelia/resources/nginx.conf
web/public/index.html

CSP is used to avoid some attacks where the hacker tries to execute
untrusted code in the browser.
The policy is to use assets hosted on the the original website and in order to make CSP work with material UI, a nonce is generated at each request of index.html and injected in the template as well as provided in the Content-Security-Policy header (https://material-ui.com/styles/advanced/#how-does-one-implement-csp)
Fix #815

[FEATURE] Add Content-Security-Policy meta to login portal.

---

internal/handlers/handler_verify.go
internal/handlers/handler_verify_test.go

This affects primarily Authelia instances running behind Traefik or
nginx ingress controllers within Kubernetes because those proxies
require that Authelia returns 302 instead of 401 after the session
has been inactive for too long.
Fix #909

[BUGFIX] Fix bad redirection behavior after inactivity using Traefik.

---

web/src/layouts/LoginLayout.tsx

* 4.8.0 deps bump changed the root containers padding from 32px to 24px
* only affects the u2f screen, this fixes the padding on the root container for the Login Layout
* this makes u2f screen layout behave the same as all of the other ones

[FIX] Layout discrepancy with U2F

---

internal/server/server.go
internal/suites/example/compose/authelia/resources/nginx.conf
web/src/App.tsx

Also:
- not hide the CSP header in the dist version of suites.
- Fix CSP errors due to FontAwesome loading stylesheets dynamically.

[BUGFIX] Fix CSP not propagated in default handler.

---

.reviewdog.yml

This will ensure that GitHub checks are identified as failures as opposed to neutral warnings.

[CI] Update reviewdog level to error

---

.dependabot/config.yml

This will allow dependabot to inform us when there are newer version of the base packages for our Dockerfiles.

[CI] Add Dockerfile monitoring to dependabot

---

.dependabot/config.yml

This will allow dependabot to inform us when there are newer ruby bundles available.

[CI] Add Gemfile.lock monitoring to dependabot

---

.buildkite/deployment.sh

If we have multiple builds to master that intend to deploy AUR packages or documentation, we must ensure that the jobs are locked and executed sequentially, not simultaneously. If they were to run simultaneously this has the ability to cause a race condition when attempting to commit the respective steps.

[CI] Prevent race conditions with appropriate deployment steps

---

.buildkite/deployment.sh

This change simplifies our pipeline and ensures that we prevent race conditions for competing jobs to master at a global level.
The hardcoded yaml pipeline in our pipeline settings are as follows:
```yaml
steps:
- label: ":pipeline: Setup Pipeline"
command: ".buildkite/pipeline.sh | buildkite-agent pipeline upload"
concurrency: 1
concurrency_group: "deployments"
if: build.branch == "master"
- label: ":pipeline: Setup Pipeline"
command: ".buildkite/pipeline.sh | buildkite-agent pipeline upload"
if: build.branch != "master"
- wait:
if: build.pull_request.repository.fork != true && build.branch !~ /^dependabot\/.*/
- block: "Public fork needs approval"
if: build.pull_request.repository.fork == true
- label: ":rocket: Setup Deployment"
command: ".buildkite/deployment.sh | buildkite-agent …
```

[CI] Set concurrency groups at a global level and simplify pipeline

---

.buildkite/deployment.sh

Pushes to master and tagged releases will have now have explicit dependencies for steps. This is specifically to prevent darwin based builds holding up execution of other steps which should not have a dependence.
The upstream hardcoded pipeline steps have already been changed to:
```yaml
steps:
- label: ":pipeline: Setup Pipeline"
command: ".buildkite/pipeline.sh | buildkite-agent pipeline upload"
concurrency: 1
concurrency_group: "deployments"
if: build.branch == "master"
- label: ":pipeline: Setup Pipeline"
command: ".buildkite/pipeline.sh | buildkite-agent pipeline upload"
if: build.branch != "master"
- wait:
if: build.pull_request.repository.fork != true && build.branch !~ /^dependabot\/.*/
- block: "Public fork needs approval"
if: build.pull_request.repository.fork == true
- label: …
```

[CI] Optimise pipeline deployments with explicit dependencies

---

.buildkite/steps/deployimages.sh
.buildkite/upstream.yml

This change ensures that CI_BYPASS works as intended and ensures that the hardcoded pipeline does not conflict with the repo provided dynamic pipeline.
The hardcoded pipeline has been changed to reflect the following:
```yaml
steps:
- label: ":pipeline: Setup Pipeline"
command: ".buildkite/pipeline.sh | buildkite-agent pipeline upload"
concurrency: 1
concurrency_group: "deployments"
if: build.branch == "master"
- label: ":pipeline: Setup Pipeline"
command: ".buildkite/pipeline.sh | buildkite-agent pipeline upload"
if: build.branch != "master"
- wait:
if: build.pull_request.repository.fork != true && build.branch !~ /^dependabot\/.*/
- block: "Public fork needs approval"
if: build.pull_request.repository.fork == true
- label: ":rocket: Setup Deployment"
command: ".buildkite/deployment.sh | …
```

[CI] Fix pipeline dependencies

---

internal/authentication/const.go
internal/authentication/file_user_provider.go
internal/authentication/password_hash.go
internal/commands/hash.go

It helps distinguish between the configuration representation of an algorithm
and the crypt representation (6 and argon2id vs sha512 vs argon2id).

[MISC] Introduce CryptAlgo type.

---

.buildkite/hooks/post-command

Prior to this change if there was a branch/PR build which had not yet published manifests and a master build running simultaneously, assuming the master build finished publishing manifests before the former it would clean up the architecture tagged containers (-{amd64,arm32v7,arm64v8}) which would result in the manifest step failing for the branch or PR build.
The aforementioned architecture containers should not be considered in either of the clean up steps because they're removed as part of a successful manifest being published.

[CI] Fix race condition on Docker tag clean up

---

internal/server/index.go

This will need to be revisited to re-introduce trusted-types when we have a clear handle on all the libraries and their implementation to support this.

[BUGFIX] Relax CSP for trusted-types

---

internal/handlers/handler_verify_test.go

Due to a [change in net/url](https://golang.org/doc/go1.14#net/url) tests need to be adjusted:
>When parsing of a URL fails (for example by Parse or ParseRequestURI), the resulting Error message will now quote the unparsable URL. This provides clearer structure and consistency with other parsing errors.

[MISC] Fix unit tests for Go 1.14+

---

internal/configuration/validator/session.go
internal/configuration/validator/session_test.go

Some users spend several hours figuring out the domain must be plain root domain instead of a wildcard. Here we try to let them know as fast as possible with a configuration check.

[MISC] Validate domain set in session is not a wildcard domain.

---

cmd/authelia/coverage_test.go
cmd/authelia/main.go
internal/configuration/reader.go
internal/configuration/reader_test.go
internal/configuration/test_resources/config_bad_quoting.yml

If the configuration yaml is poorly indented or special values are not appropriately escaped Authelia attempts to load said configuration and fails.
This attempts to unmarshal the config into an empty interface to catch and warn on malformed yaml.
Using the example from issue https://github.com/authelia/authelia/issues/1053#issuecomment-634791662
```yaml
host: 0.0.0.0
port: 9091
log_level: debug
jwt_secret: RUtG9TnbXrOl1XLLmDgySw1DGgx9QcrtepIf1uDDBlBVKFZxkVBruYKBi32PvaU
default_redirection_url: example.com
totp:
issuer: example.com
period: 30
skew: 1
authentication_backend:
file:
path: /etc/authelia/users_database.yml
access_control:
default_policy: deny
rules:
- domain: example.com
policy: bypass
- domain: *.example.com
policy: one_factor
session:
name: authelia_session
secret: …
```

[MISC] Catch and warn on malformed configuration yaml

---

.buildkite/deployment.sh
.buildkite/hooks/post-checkout
.buildkite/hooks/post-command
.buildkite/hooks/pre-artifact
.buildkite/hooks/pre-command
.buildkite/hooks/pre-exit
.buildkite/pipeline.sh
.buildkite/steps/aurhelper.sh
.buildkite/steps/aurpackages.sh
.buildkite/steps/buildimages.sh
.buildkite/steps/deployimages.sh
.buildkite/steps/e2etests.sh
.buildkite/steps/ghartifacts.sh
.buildkite/steps/syncdoc.sh
bootstrap.sh
cmd/authelia-scripts/authelia-scripts
compose/local/setup.sh
internal/suites/example/compose/kind/entrypoint-dashboard.sh
internal/suites/example/kube/bootstrap-dashboard.sh

Hardcoding /bin/bash prevents some users (e.g. NixOS users) from running the scripts.
I got Standalone running and have not done further testing.

[MISC] Use /usr/bin/env bash for scripts

---

compose/local/setup.sh

As files were moved to accommodate the new `/config` volume structure the `setup.sh` for the local compose bundle also requires updating to point to the new file locations.
Fixes #1129.

[BUGFIX] Fix local compose bundle regression from #1113

---

Dockerfile
Dockerfile.arm32v7
Dockerfile.arm64v8

This change ensures that we strip debug information from the generated binaries in order to keep the files smaller.
Summary of the options for these are as follows, we have been running with `-w` for quite some time now:
```
-w    disable DWARF generation
-s    disable symbol table

[MISC] Strip debug information from compiled binaries

---

docs/_layouts/default.html

This fixes a minor regression due to #1158.
As there was significant styling changes and due to our introduction of the github fork ribbon for the docs the layout also needed to be updated.

[DOCS] Fix just-the-docs theme styling

---

.github/probot.js

There is an issue with codecov where if a PR is made from a forked master branch this manages to assume itself as the default codecov branches, this in turn causes coverage synchronisation issues for our repo.

[CI] Ignore CI/CD and notify for forked master branches

---

web/src/App.tsx
web/src/hooks/AssetPath.ts
web/src/hooks/BasePath.ts
web/src/hooks/Configuration.ts
web/src/index.tsx
web/src/services/Api.ts
web/src/utils/AssetPath.ts
web/src/utils/BasePath.ts
web/src/utils/Configuration.ts

When fixing the templating of asset locations #1150 this introduced a regression which seems related to an import chain/ordering issue specifically when running in the development workflow.
By virtue of this, anything residing in `web/src/hooks/` that was not a true React hook has now been moved to `web/src/utils/`.

[DEV] Fix webpack for development workflow

---

internal/handlers/errors.go
internal/handlers/handler_register_u2f_step1_test.go
internal/handlers/handler_sign_u2f_step1_test.go
internal/handlers/handler_verify.go
internal/handlers/handler_verify_test.go
internal/middlewares/errors.go
internal/middlewares/identity_verification_test.go

This is a PR for issue #1279 
It fixes several typos in the word "Forwarded"
Edit (by James): This will close #1279 if merged

[MISC] Fixed typo in X-Forwarded headers

---

cmd/authelia-scripts/cmd_docker.go
cmd/authelia-scripts/main.go
internal/authentication/file_user_provider_test.go
internal/configuration/validator/authentication.go
internal/configuration/validator/secrets.go
internal/handlers/handler_verify_test.go
internal/notification/smtp_notifier.go
internal/storage/sql_provider_test.go

This also includes fixes for linter errors from a golangci-lint update.

[CI] Update QEMU to v5.1.0-2

---

Dockerfile
Dockerfile.arm32v7
Dockerfile.arm64v8

The `WORKDIR` needs to be set early to ensure that the files are copied into the appropriate directory.
This is a minor regression that was introduced in af2ae328e7cb810d2282ae615791cc10b840b9a9.

[BUGFIX] Fix Dockerfile WORKDIR

---

config.template.yml
docs/configuration/notifier/smtp.md
internal/configuration/schema/notifier.go
internal/configuration/validator/const.go
internal/configuration/validator/notifier.go
internal/notification/smtp_notifier.go

* add docs
* add configuration option for SMTP called `identifier`
* default should act the same as before
Closes #1146 if merged.

[BUGFIX] Add ability to specify SMTP HELO/EHLO identifier

---

Dockerfile
Dockerfile.arm32v7
Dockerfile.arm64v8

One thing to consider would be if the user is running Authelia with TLS enabled, perhaps an option would be to set a runtime variable that specifies TLS/Non-TLS and that can be utilised to determine the switch for http/https in the health check?
EDIT: Because we can't set the shell's environment variable inside Go's context I think we just stick to adding the healthcheck for the default deployment option (non-TLS) and perhaps add some docs regarding adjusting the healthcheck if the user deploys with TLS, thoughts?
Closes #1423.

[FEATURE] Add health checks to containers

---

internal/server/server.go

The warnings are currently limited to Linux based deployments, however this covers both container and host (static binary) based deployments.
We could potentially look to expand this to FreeBSD in future too.
Closes #1391.

[MISC] Warn for poorly tuned argon2id deployments

---

web/src/views/LoginPortal/SecondFactor/OneTimePasswordMethod.tsx
web/src/views/LoginPortal/SecondFactor/PushNotificationMethod.tsx
web/src/views/LoginPortal/SecondFactor/SecurityKeyMethod.tsx

https://github.com/authelia/authelia/pull/1403/commits/b34b10322bee7193b9ff6ba05001bcba7fc0745e introduced a regression where including deps in the associated useCallback functions would cause React to re-render components.
This resulted in unexpected symptoms like multiple Duo push requests, even if a successful or errored request had already been received.
Empty deps/no re-rendering for the respective callbacks is an expected result therefore we can safely ignore these issues the linter is suggesting needs to be fixed.

[BUGFIX] Fix re-rendering callbacks

---

docs/configuration/session.md

This looks like it just fell out of sync with what actually already exists within the [`config.template.yml`](https://github.com/authelia/authelia/blob/695cd5bf8f5d964ffff715c1ea14c240299c6899/config.template.yml#L291).
Fixes #1411.

[DOCS] Update session docs to clarify encryption

---

config.template.yml
docs/configuration/miscellaneous.md
docs/security/measures.md
internal/logging/logger.go
internal/suites/example/compose/nginx/portal/nginx.conf
internal/suites/example/compose/squid/squid.conf

If Authelia is restarted when a `log_file_path` is defined, upon restart the log file is overwritten.
This change ensures that the log file will be appended to. Users will need to ensure that they rotate/truncate this over time especially if running in `debug` or `trace`.
Fixes #1294.

[MISC] Append log file instead of overwriting

---

web/.env.development
web/.env.production
web/public/index.html
web/src/setupTests.js
web/src/utils/Configuration.ts

Since merging #1135 and utilising Go templating to enable/disable the rememeber me and password reset features these have stopped working in the development workflow.
During frontend development if someone wants to enable/disable these features they should modify the `.env.development` file accordingly.

[CI] Fix development workflow

---

internal/suites/const.go
internal/suites/suite_network_acl_test.go
internal/suites/webdriver.go

The development workflow expects chromedriver to be run on the host on port `4444`.
There is currently no mechanism to modify this behaviour at runtime, so if another service is running on `4444` tests will just fail silently.
This change introduces the `CHROMEDRIVER_PORT` environment variable which can be utilised to set a custom port.

[CI] Add ability to customise the chromedriver port

---

internal/handlers/handler_verify.go
internal/handlers/handler_verify_test.go

https://github.com/authelia/authelia/commit/a83ccd71887cb843adce10fe14d630fbf3ac9bec introduced a regression where if a misconfigured deployment presented an empty emails array, setting the `Remote-*` headers would fail and in turn would result in Authelia crashing.
If the emails array is empty we now set the `Remote-Email` header to an empty string.
Fixes #1451.

[BUGFIX] Prevent crash when email has not been set

---

.buildkite/hooks/post-command
Dockerfile.coverage
cmd/authelia-scripts/cmd_suites.go
internal/server/const.go
internal/server/index.go
internal/server/server.go
internal/suites/LDAP/configuration.yml
internal/suites/example/kube/authelia/configs/configuration.yml
internal/suites/example/kube/authelia/deployment.yml
internal/suites/webdriver.go
web/craco.config.js
web/package.json
web/yarn.lock

This change will allow us to collect frontend code coverage from our Selenium based integration tests.
Given that the frontend is embedded into the Go binary and the integration tests run with a compiled binary in Docker this poses some issues with the instrumented code and the ability for it to run in this manner.
To fix this we need to relax Authelia's CSP for the integration tests. This is achieved by setting the env variable `ENVIRONMENT` to `dev`.

[CI] Collect coverage from frontend during integration tests

---

healthcheck.sh

When merged to `master` #1461 can be closed.
The configuration.yml might contain CRLF characters. If that's the case, they are included in the results of sed, which breaks the healthcheck, so remove any CR characters in the host/port variables.

Fix healthcheck failing because of CRLF in configuration.yml

---

healthcheck.sh

The configuration.yml might contain CRLF characters. If that's the case, they are included in the results of sed, which breaks the healthcheck, so remove any CR characters in the host/port variables (#1483).
This script also now determines the host for Docker healthcheck from the `configuration.yml` that Authelia is started with.
Fixes #1461.

[BUGFIX] Fix Docker healthcheck script

---

cmd/authelia-scripts/cmd_bootstrap.go
cmd/authelia/main.go
internal/notification/smtp_notifier.go

This change aims to utilise the correct logging interface consistently.
The only instances where stdlib log is utilised is for tests and when commands that Authelia supports; for example certificate generation, password hashing and config validation.

[MISC] Consistently utilise correct logging interface

---

healthcheck.sh
internal/handlers/handler_health.go
internal/server/server.go
internal/utils/aes.go

This change points the Docker containers healthcheck to the dedicated `/api/health` endpoint and also includes support for Authelia running with a path prefix.

[FEATURE] Create dedicated health endpoint

---

cmd/authelia/main.go
config.template.yml
docs/configuration/miscellaneous.md
internal/configuration/schema/configuration.go
internal/configuration/validator/configuration_test.go
internal/configuration/validator/const.go
internal/logging/logger.go
internal/logging/logger_test.go

This change adds the ability to format Authelia's log output as JSON.
Example below:
```
{"level":"info","msg":"Logging severity set to info","time":"2020-01-01T00:00:00+11:00"}
{"level":"info","msg":"Authelia is listening for non-TLS connections on 0.0.0.0:9091","time":"2020-01-01T00:00:00+11:00"}
```
Closes #1456.

[FEATURE] Add JSON log formatting option

---

config.template.yml
docs/configuration/authentication/ldap.md
internal/configuration/validator/authentication.go
internal/configuration/validator/authentication_test.go

Not including the `username_attribute` in the `users_filter` will cause issues with the LDAP session refresh and will result in session resets when the refresh interval has expired.
This change makes said attribute mandatory for the `users_filter`.
Fixes #1357.

[BUGFIX] Make username_attribute a mandatory placeholder in users_filter

---

.buildkite/hooks/post-command
.codecov.yml

This change ensure that files are not incorrectly identified and uploaded to codecov as reports.
Also as we do not utilise service workers in React, ignoring `serviceWorker.ts` gives more accurate coverage percentages.

[CI] Exclude non-coverage files from codecov upload

---

docs/configuration/access-control.md

[DOCS] Add a note on regexps in ACLs.

---

internal/handlers/const.go
internal/handlers/handler_reset_password_step2.go
internal/suites/LDAP/configuration.yml
internal/suites/example/compose/ldap/ldif/01-pp.ldif
internal/suites/example/compose/ldap/ldif/02-ppcfg.ldif
internal/suites/example/compose/ldap/ldif/03-base.ldif
internal/suites/example/compose/ldap/ldif/04-access.ldif
internal/suites/example/compose/ldap/ldif/access.rules
internal/suites/suite_ldap_test.go
internal/utils/strings.go
internal/utils/strings_test.go
web/src/services/Api.ts
web/src/services/Client.ts
web/src/views/ResetPassword/ResetPasswordStep2.tsx
web/tsconfig.json

Further to the discussion over at #361, this change now ensures that OpenLDAP password complexity errors are caught and appropriately handled.
This change also includes the PasswordComplexity test suite in the LDAP integration suite. This is because a ppolicy has been setup and enforced.

[MISC] Catch OpenLDAP ppolicy error

---

cmd/authelia-scripts/cmd_suites.go
internal/handlers/handler_configuration.go
internal/handlers/handler_firstfactor.go
internal/handlers/handler_logout_test.go
internal/handlers/handler_register_totp.go
internal/handlers/handler_register_u2f_step1.go
internal/handlers/handler_register_u2f_step1_test.go
internal/handlers/handler_register_u2f_step2.go
internal/handlers/handler_reset_password_step1.go
internal/handlers/handler_sign_duo_test.go
internal/handlers/handler_sign_totp_test.go
internal/handlers/handler_sign_u2f_step2_test.go
internal/handlers/handler_state.go
internal/handlers/handler_state_test.go
internal/handlers/handler_user_info.go
internal/handlers/handler_user_info_test.go
internal/handlers/response.go
internal/suites/action_2fa_methods.go
internal/suites/action_reset_password.go
internal/suites/action_totp.go
internal/suites/scenario_regulation_test.go
internal/suites/suite_kubernetes.go
internal/suites/webdriver.go
web/tsconfig.json

This is mostly a quality of life change.
When we first implemented the errcheck linter we ignored a number of items in our legacy codebase with intent to revisit down the track.
There's a only a few leftover TODO's, these have been left for the team to discuss on Matrix and agree on the way forward.

[MISC] Refactor and address most errcheck linter ignores

---

config.template.yml
docs/configuration/authentication/ldap.md

Based on #1517 
Adding a comment to the LDAP group section of the config file to tell users they need to use a different group_filter if their LDAP groups use the `groupOfUniqueNames` structure instead of the expected `groupOfNames` structure.
Not doing so result in Authelia not finding the groups for the user and not authorizing group-based access.

Add config example for LDAP groupOfUniqueNames group structure

---

internal/suites/action_totp.go
web/src/views/DeviceRegistration/RegisterOneTimePassword.tsx

This change provides the TOTP secret which allows users to copy and utilise for password managers and other applications.
**EDIT:** I've made a slight modification to the view, refer to my [comment below](https://github.com/authelia/authelia/pull/1551#issuecomment-750701251).
Closes #1509.

[FEATURE] Display TOTP secret on device registration

---

docs/deployment/supported-proxies/nginx.md

This PR updates the trusted IP range in the nginx example.
The example only trusts the correct IP from the Private Internets (as described here: https://tools.ietf.org/html/rfc1918) however one of the ranges was too large. 
The correct ranges are:
-  `10.0.0.0/8`
-  `172.16.0.0/12`
-  `192.168.0.0/16`
Source: https://tools.ietf.org/html/rfc1918#section-3
Happy New Year!

[DOC] Correct private IP range

---

docs/configuration/miscellaneous.md
internal/utils/certificates.go

* add .crt to the PEM extensions scanned for
* fix documentation on the extensions allowed
* add trace logging to the loading process to help debug in the future
If merged, fixes #1588

[BUGFIX] Fix incorrect docs and Certificate PEM extensions

---

.github/probot.js

This change updates the PR commentary specifically around linting.
We now also allow users to submit PRs to Authelia from forked `master` branches, this was previously disabled as it caused issues with codecov.

[CI] Update PR commentary

---

.github/probot.js

An extra filter needed to be removed and pull request branch filtering on Buildkite changed to ensure that forked `master` branches actually receive CI/CD treatments.

[CI] Fix CI/CD for forked master branches

---

README.md

The shield.io badge on the readme was showing the tag 'deprecate-ldap-tls-4.28' along with the incorrect size.
The Pull Request contains a fix where the latest tag is now used for the docker tag and size badge.

[DOCS] Specify docker tag for readme badges

---

internal/logging/const.go
internal/logging/logger.go

In some scenarios if a user has a `log_file_path` specified and a TTY seems to be detected this causes terminal coloring outputs to be written to the file. This in turn will cause issues when attempting to utilise the log with the provided fail2ban regexes.
We now override any TTY detection/logging treatments and disable coloring/removal of the timestamp when a user is utilising the text based logger to a file.
Fixes #1480.

[BUGFIX] Disable colored logging outputs when file is specified

---

web/src/views/LoginPortal/SecondFactor/MethodSelectionDialog.tsx

On the method selection page previously the OTP option had a circle which gradually reduced in size and eventually reset, this was a intended as a visual indicator for a time based OTP.
Currently this is broken and in turn we see the following:
With this fixed implemented we see the following:

[MISC] Fix OTP countdown circle

---

.renovaterc

This PR removes the hourly limit for the number of PRs that renovate will raise.

ci: update renovate configuration

---

.renovaterc

This change is to ensure that our CI workers are not flooded with jobs that fail.
This setting will be removed when the initial backlog has been merged.

ci(renovate): disable automatic rebasing

---

.buildkite/deployment.sh
.buildkite/pipeline.sh
.buildkite/steps/buildimages.sh

This PR modifies the Buildkite CI pipeline with the following changes:
* Add `SECURITY.md` to CI_BYPASS
* Skip Docker {amd64,arm32v7,arm64v8} builds for renovate PRs
* Ensure Deploy Manifest step only is assigned to deployment nodes

ci(buildkite): update buildkite deployment steps

---

Dockerfile.coverage
healthcheck.sh

This change ensures that the integration test container also utilises the health check script to ensure coverage for this area of code.

test(handlers): add health check to coverage build

---

.buildkite/deployment.sh
.buildkite/pipeline.sh

This change prevents the unit/integration testing and image deployment similar to other docs only changes.

ci: consider .all-contributorsrc a docs file for the pipeline

---

web/src/views/LoginPortal/SecondFactor/OTPDial.tsx

#1584 introduced a regression due to the way layouts are addressed with [CSS normalization](https://material-ui.com/components/css-baseline/#layout).
This PR ensures that the OTP input box will remain a `content-box` to avoid any text display and box sizing issues caused by padding.
The OTP input has also been changed to only accept numbers.
Fixes #1720.

fix(web): fix otp input box with themes

---

.buildkite/pipeline.sh

Due to the unpredictability of changes that Renovate can submit this PR will allow us to control the number of jobs that will run simultaneously per step.

ci(buildkite): add concurrency limits to build and test steps

---

.buildkite/pipeline.sh

Split out unit-testing jobs to ensure that the workloads are evenly spread.

ci(buildkite): optimise job to agent assignment

---

docs/deployment/supported-proxies/haproxy.md
docs/deployment/supported-proxies/nginx.md
docs/deployment/supported-proxies/traefik1.x.md
docs/deployment/supported-proxies/traefik2.x.md
docs/features/single-factor.md
internal/handlers/const.go
internal/handlers/handler_verify.go
internal/handlers/handler_verify_test.go

When `/api/verify` is called with `?auth=basic`, use the standard `Authorization` header instead of `Proxy-Authorization`.
Fixes #1353.

feat(handlers): authorization header switch via query param to /api/verify

---

.buildkite/pipeline.yml
.buildkite/steps/buildimages.sh
.github/probot.js

Restores the dependabot rules in buildkite for the purpose of security fixes which are still handled by dependabot.

ci: restore dependabot rules

---

README.md
internal/authentication/password_hash.go

Improve security with usage of the crypto/subtle ConstantTimeCompare() method for hash comparison.
Fixes #1799

refactor(authentication): use crypto constant time compare

---

internal/server/server.go
internal/server/template.go
internal/suites/scenario_backend_protection_test.go

Returns a 404 instead of 200 on bad API endpoints.
Co-authored-by: Clément Michaud <clement.michaud34@gmail.com>
Fixes #1520
Closes #1534

fix(server): send 404 on missing api endpoints instead of 200

---

docs/configuration/access-control.md

I missed documenting this change, but prior to 4.27.0 the query param was never considered when matching resources. But that's no longer the case.
Fixes #1817

docs(authorization): document changed resources behavior

---

web/package.json

During a `yarn start` the react frontend would throw the following errors during compilation:
```
Starting the development server...
Compiled with warnings.
./src/index.css (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-4-1!./node_modules/postcss-loader/src??postcss!./src/index.css)
Warning
Greetings, time traveller. We are in the golden age of prefix-less CSS, where Autoprefixer is no longer needed for your stylesheet.
./node_modules/@fortawesome/fontawesome-svg-core/styles.css (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-4-1!./node_modules/postcss-loader/src??postcss!./node_modules/@fortawesome/fontawesome-svg-core/styles.css)
Warning
Greetings, time traveller. We are in the golden age of prefix-less CSS, where Autoprefixer is no longer needed for your stylesheet. …
```

fix(web): fix compilation and running in development mode

---

docs/configuration/secrets.md
internal/authentication/file_user_provider_test.go
internal/configuration/const.go
internal/configuration/reader.go
internal/configuration/reader_test.go
internal/configuration/test_resources/config.yml
internal/configuration/validator/authentication.go
internal/configuration/validator/authentication_test.go
internal/configuration/validator/configuration.go
internal/configuration/validator/configuration_test.go
internal/configuration/validator/const.go
internal/configuration/validator/keys.go
internal/configuration/validator/secrets.go
internal/configuration/validator/secrets_test.go
internal/configuration/validator/server_test.go
internal/configuration/validator/storage.go
internal/configuration/validator/storage_test.go
internal/utils/certificates_test.go
internal/utils/const.go

Adds the redis sentinel secret and refactors the entire secret derivation process to make it more consistent.

fix: redis sentinel secret missing

---

compose/lite/docker-compose.yml
compose/local/docker-compose.yml
docs/deployment/deployment-lite.md

Traefik does not add routes for containers via the Docker provider if the health check does not return healthy, this causes inadvertent user experience issues when attempting the pre-made compose examples.
This change removes the health checks for said examples and also ensures that Traefik logs are written to stdout so a user can view them within the Docker container logs.
Fixes #1864.

fix: remove health checks on compose examples

---

compose/local/setup.sh

Running the script with missing prerequisites
doesn't fail, but instead warns the user
that return statements aren't allowed here.
---
I didn't have ``docker-compose`` installed, but the script continued to run instead of stopping immediately. Seems like an oversight?

fix: exit setup.sh if missing pre-requisites

---

internal/notification/file_notifier.go

Attempting to run Authelia with least privilege principle as the `nobody` user and a file based notifier will cause issues during start up as the user cannot remove the notification file.
Given that `ioutil.WriteFile` truncates the file before writing the removal is not necessary.
Fixes #1846.

fix(notification): don't remove file based notifier on start up

---

docs/community/example-of-authelia-lite-on-docker-swarm.md

The authelia lite has been successfully deployed to my docker swarm after adding some modifications to: https://github.com/authelia/authelia/pull/1112
http://traefik.wuhanstudio.cc/
http://public.wuhanstudio.cc/
http://secure.wuhanstudio.cc/

docs: add an example of deploying authelia lite on docker swarm

---

docs/home/supported-proxies.md

I'm adding this page because after doing a quick review of the doc, it was not easy to find out this basic information.

docs: Add a page listing supported proxies.

---

internal/suites/example/compose/kind/config.yml

The annotation was previously pointing to the incorrect registry so the registrycache was not being utilised.

fix(suites): ensure k8s suite utilises the registry cache

---

config.template.yml
docs/configuration/session/index.md
docs/security/measures.md
internal/configuration/config.template.yml
internal/configuration/schema/session.go
internal/configuration/validator/const.go
internal/configuration/validator/session.go
internal/configuration/validator/session_test.go
internal/session/provider_config.go
internal/session/provider_config_test.go

This implements a change to the default behaviour of the cookies generated by the sessions package. The old behaviour was to set the SameSite=None, this changes it to SameSite=Lax. Additionally this puts the option in the hands of the end-user so they can decide for themselves what the best option is.

fix(session): ensure default cookie samesite value is lax

---

cmd/authelia/main.go

Instead of using panic() when an unknown error was detected on OP initialization, use logger.Fatalf. This provides a more useful output to the user.

refactor: use fatal log message on oidc init error

---

cmd/authelia-scripts/cmd_docker.go
internal/utils/exec.go

This change will ensure that if the curl command for the cleaning of Docker tags on DockerHub fails it will be reattempted up to 2 more times (total of 3) with a 10 second sleep between each attempt.
The clean tag logic itself within curl attempts to execute the http request upto 3 times so this will ensure a maximum of 9 attempts.

fix(cmd): retry clean tag logic for dockerhub

---

docs/configuration/secrets.md

This updates secrets configuration for 4.29.0 and fixes an existing issue.
Fixes #1977

docs: update secrets configuration

---

go.mod
go.sum

This is necessary to force the latest version of go-sqlite3 due to an issue with the release lifecycle upstream and due to deep dependencies.

refactor: forcibly use latest go-sqlite3

---

internal/handlers/oidc.go

This is so the sig key used to sign the JWT can be verified using the JWKS endpoint.
Fixes #1979

fix(handlers): include the jwk key id in the jwt for validation

---

.buildkite/steps/e2etests.sh

Allows granular control for node assignment on the high availability testing suite.

ci(buildkite): add tag for highavailability suite

---

.dockerignore
Dockerfile
Dockerfile.arm32v7
Dockerfile.arm64v8
Dockerfile.coverage

This change is so that each of the COPY/RUN steps occurs in a single layer which should theoretically decrease build times.

build: optimize docker builds

---

.golangci.yml
cmd/authelia-scripts/cmd_suites.go
internal/middlewares/authelia_context.go
internal/suites/kubernetes.go
internal/suites/suite_kubernetes.go
internal/utils/exec.go

Remove deprecated `golint` linter and replace with `revive` linter.
Also fix outstanding issues due to upgraded linters.

ci(golangci-lint): replace golint with revive linter

---

web/src/views/DeviceRegistration/RegisterOneTimePassword.tsx

Some qrcode reader are struggling to decode the qrcode because there
no clear border between the qrcode image and the page background in dark
mode. This fix add a white padding so that the border is now obvious.
Fix: #1777

fix(web): add white padding around qrcode image

---

internal/handlers/const.go
internal/handlers/handler_reset_password_step2.go

This responds to the client with the correct error when used with Synology LDAP servers.

feat(handlers): synology password complexity err on reset

---

docs/getting-started.md
examples/compose/local/setup.sh

The local setup script expects to be run as root and would only work on a fresh clone of the repo. Now if not run as root the user will be prompted for sudo elevation at the beginning of the script and the script will also survive re-runs on a dirty clone.
Fixes #1864.

feat(examples): improve local setup script

---

go.mod
go.sum
internal/handlers/handler_register_u2f_step1_test.go
internal/handlers/types_oidc.go
internal/middlewares/identity_verification.go
internal/middlewares/identity_verification_test.go
internal/middlewares/types.go

This replaces github.com/dgrijalva/jwt-go and github.com/form3tech-oss/jwt-go with github.com/golang-jwt/jwt which will be the maintained package going forward.

build(deps): replace jwt-go

---

cmd/authelia/main.go
internal/authorization/authorizer.go
internal/authorization/authorizer_test.go
internal/authorization/const.go
internal/authorization/util.go
internal/handlers/handler_configuration.go
internal/handlers/handler_configuration_test.go
internal/handlers/handler_firstfactor_test.go
internal/handlers/handler_verify_test.go
internal/mocks/mock_authelia_ctx.go
internal/suites/scenario_redirection_check_test.go

This resolves an issue where if you have zero two_factor ACL rules but enabled two_factor OIDC clients, 2FA is reported as disabled.

fix(authorization): configuration reports 2fa disabled with 2fa oidc clients

---

internal/suites/Standalone/configuration.yml

Allows capturing of code coverage for the `auto` theme in the Standalone suite.

test(web): integration test auto theme

---

Dockerfile.arm32v7
Dockerfile.arm64v8
cmd/authelia-scripts/cmd_docker.go

QEMU binaries no longer need to be baked into containers.

refactor: drop qemu binary requirement

---

.buildkite/pipeline.sh
Dockerfile.coverage
cmd/authelia-scripts/cmd_build.go
cmd/authelia-scripts/cmd_ci.go
cmd/authelia-scripts/cmd_docker.go
cmd/authelia-scripts/main.go
web/.env.production

The `authelia-scripts` helper currently performs steps to move files around in different stages of development and CI/CD.
We now utilise the `BUILD_PATH` environment variable to adjust the output directory for the web frontend from the default of `./web/build/` simplifying the helper somewhat.
Additionally we no longer build the Go binary in the unit test stage of our CI/CD as this is not necessary.

refactor: cra build path

---

internal/suites/example/compose/authelia/resources/run-backend-dev.sh

following #2101 I was receiving the following error when using the authelia scripts suite for developing
```
[00] # runtime/cgo
[00] cgo: exec gcc: exec: "gcc": executable file not found in $PATH
```
adding the CGO_ENABLED=0 before the dlv build command fixes the issue
must have been overlooked :)

fix(suites): disable cgo for delve during development

---

cmd/authelia/main.go
internal/authentication/const.go
internal/authentication/ldap_user_provider.go
internal/authentication/ldap_user_provider_test.go

This PR adds a startup check to the LDAP authentication backend. It additionally adds support for checking supportedExtension OIDs, currently only checking passwdModifyOID (1.3.6.1.4.1.4203.1.11.3). This can relatively easily be enhanced to add detection for other rootDSE capabilities like supportedControl and supportedCapabilities as necessary.

feat(authentiation): check ldap support for extended operations on startup

---

cmd/authelia/main.go
internal/authentication/ldap_user_provider.go

This is so on startup administrators who have a LDAP server implementation that may not support password hashing by default are clearly warned. This only triggers if the disable password reset option is not enabled, we cannot find the extension OID for the Extended Password Modify Operation, and the implementation is not Active Directory. Active Directory has it's own method for this which doesn't advertise the extension.

refactor(authentication): log ldap warning on startup in rare condition

---

internal/authentication/ldap_connection_factory.go
internal/authentication/ldap_connection_factory_mock.go
internal/authentication/ldap_user_provider.go
internal/authentication/ldap_user_provider_test.go

This was tested for OpenLDAP, I am unable to test for ActiveDirectory.

feat(authentication): use the passwordmodify exop for pwd resets with ldap

---

internal/authentication/ldap_user_provider.go
internal/authentication/ldap_user_provider_test.go

The recent ldap changes in cb71df5 left a connection to the LDAP server open at startup. This resolves this which prevents an ugly log message and unnecessary open sockets.

fix(authentication): ldap connection left open

---

docs/configuration/authentication/ldap.md
internal/configuration/schema/authentication.go
internal/suites/ActiveDirectory/configuration.yml

This adds a performance change to the default Active Directory users filter. Basically as per TechNet the (sAMAccountType=805306368) filter is the same as (&(objectCategory=person)(objectClass=user)) except the performance is better.

perf(authentication): improve active directory default users filter

---

docs/configuration/identity-providers/oidc.md

This fixes a few anchor issues in the OpenID Connect docs, as well as adds some additional references and fixes the name of one of the endpoints.

docs(oidc): misc docs fixes and additional references

---

internal/handlers/handler_verify.go
internal/handlers/handler_verify_test.go
internal/suites/suite_standalone_test.go

When a request occurs, if the browser is not performing a HTTP GET/HEAD request, the 302 status code is not valid. This commit resolves this. MDN: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/302. This PR changes the behaviour, so that if the request method is blank, `GET`, `HEAD`; the response code is `302`, otherwise it is `303`.

fix(handlers): send status 303 auth requests that are not get/head

---

docs/community/oidc-integrations.md
internal/handlers/const.go
internal/handlers/handler_firstfactor.go
internal/handlers/handler_firstfactor_test.go
internal/handlers/handler_logout.go
internal/handlers/handler_oidc_wellknown.go
internal/handlers/handler_register_totp.go
internal/handlers/handler_register_u2f_step1.go
internal/handlers/handler_register_u2f_step1_test.go
internal/handlers/handler_register_u2f_step2.go
internal/handlers/handler_reset_password_step1.go
internal/handlers/handler_reset_password_step2.go
internal/handlers/handler_sign_duo.go
internal/handlers/handler_sign_totp.go
internal/handlers/handler_sign_u2f_step1.go
internal/handlers/handler_sign_u2f_step2.go
internal/handlers/handler_user_info.go
internal/handlers/handler_verify.go
internal/handlers/handler_verify_test.go
internal/handlers/oidc_register.go
internal/handlers/response.go
internal/middlewares/authelia_context.go
internal/middlewares/const.go
internal/middlewares/identity_verification.go
internal/server/options_handler.go
internal/server/server.go
internal/suites/suite_standalone_test.go
internal/utils/const.go
internal/utils/strings.go

This changes the way XML HTTP requests are handled on the /api/verify endpoint so that they are redirected properly using a 401 instead of a 302/303. Additionally implements some style refactoring.

fix(handlers): handle xhr requests to /api/verify with 401

---

web/src/views/LoginPortal/FirstFactor/FirstFactorForm.tsx

This is for a better user experience, specifically it makes it so when users tab through the elements in the login form they are selected in a logical order.
Fixes #2204

fix(web): move reset password to after sign in

---

.github/ISSUE_TEMPLATE/config.yml
CONTRIBUTING.md
README.md
SECURITY.md
docs/about-us.md
docs/community/index.md
docs/deployment/deployment-kubernetes.md

This updates and unifies the contact options so it is easier to maintain. All contact options now link back to one of two locations, and both of these locations are a copy and paste for the most part.

docs: update and unify contact options

---

.buildkite/deployment.sh
.buildkite/pipeline.sh

This skips integration tests for any commits/PR's that only make changes to the examples/ folder as it's not a change that requires this check.

ci(buildkite): skip integration test stage for examples

---

internal/handlers/const.go
internal/handlers/handler_firstfactor.go

This is so the user banned API message is consistent with other authentication failed messages, even in the API.
Fixes #2195

fix(handlers): make user banned message consistent

---

docs/deployment/deployment-lite.md
examples/compose/lite/README.md

This ensures users checkout the latest tagged release when using the lite deployment.

docs: fix missing line from the lite guide

---

.buildkite/pipeline.sh

This ensures that the test concurrency gate step does not run on tagged releases are the integration steps are also skipped.

ci(buildkite): make test concurrency gate conditional

---

.buildkite/steps/aptdeploy.sh

Image links in the apt repo README.md were broken as the file uploaded without the necessary modifications.

ci(buildkite): fix apt repo readme

---

.buildkite/steps/deployimages.sh

Occasionally during a manifest deployment tags can be removed and the step may fail. To ensure the manifest step can be completed successfully it would require re-pushing the tags that had been removed.
Turning on the `permit_on_passed` option allows us to control this all through the Buildkite interface as opposed to manual intervention.

ci(buildkite): allow retry on successful docker deploy steps

---

internal/commands/root.go

The changes in the koanf commit a7e867a699a77f0b9d564defd81094fd410e4404 introduced a regression in the startup procedure that prevented the option to disable the startup check from having an effect. This ensures the startup check is not performed if it is disabled as it was intended.

fix(notifier): regression in startup check

---

healthcheck.sh

The healthcheck will always return 0 (healthy) since we don't source the env file before checking the ENV var.

fix: healthcheck always returns healthy

---

internal/configuration/validator/const.go

This is so an unexpected error doesn't occur when someone uses the new ldap timeout key which we missed adding to the list of valid keys in b2a49e1780041943862590984070a2268a87d823.

fix(configuration): ldap timeout option not recognized as valid

---

docs/configuration/index.md
docs/configuration/migration.md

This adds some additional information about configuration on k8s for version 4.30+.

docs(configuration): add migration note about k8s

---

.buildkite/deployment.sh
.buildkite/steps/buildimages.sh

This permits manual retry on specific steps which can cause problematic issues for example when a node runs out of disk space.
By allowing this we should be able to recover problematic builds instead of forcing a complete rebuild which may be undesirable on the `master` or other production branches.

ci(buildkite): allow manual retry on successful steps

---

docs/configuration/migration.md
internal/configuration/validator/const.go
internal/configuration/validator/notifier.go
internal/configuration/validator/notifier_test.go

This ensures the notifier logs are more accurate to give people a clear picture of if they either have no notifier specified or multiple.

fix(configuration): make notifier logging consistent and more accurate

---

docs/community/oidc-integrations.md

Heya! Just did some trial and error until I managed to get Nextcloud to auth through OpenID Connect with Authelia and figured I'd post the callback URL I used to get it working. 
I put the latest stable nextcloud version (currently `22.1.0`) as the minimum version because that's what I have at hand to test on but since the OIDC login stuff actually depends on an app from their app store and seems to be available going back several versions it might very well work just the same with older installations. 
Let me know if you need any more info or if there are any tests/best-practices/whatever I should follow with the PR. 
Thanks for the awesome work on this :D.

docs: add nextcloud community tested oidc apps

---

web/package.json

The current eslint glob pattern is not Windows friendly, this change works for both Linux and Windows.

refactor(web): eslint glob pattern

---

api/openapi.yml

The following schemas for `/api/checks/safe-redirection` were missed in #2082:
* handlers.checkURIWithinDomainRequestBody
* handlers.checkURIWithinDomainResponseBody
Fixes #2338.

fix(api): /api/checks/safe-redirection missing schemas

---

internal/suites/example/compose/authelia/resources/run-backend-dev.sh

Due to how the dev workflow allows Authelia developers to run the binary hot-reloaded we should disable the Docker health check for said workflow to prevent accidental commits upstream.

fix(suites): prevent dev workflow overriding .healthcheck.env

---

internal/server/server.go
web/.commitlintrc.js

Given the fact that many Linux OSes are defaulting to CGroups v2 and also Authelia changing the default memory config for argon2id this warning is now obselete.
Fixes: #2369.

fix(server): remove obselete memory check warning

---

.buildkite/annotations/artifacts
.buildkite/hooks/pre-artifact
.buildkite/hooks/pre-command
.buildkite/steps/ghartifacts.sh
Dockerfile
cmd/authelia-scripts/cmd_build.go

This change ensures that all Authelia binaries which are compiled and distributed are hardened with the following standards:
* RELRO
* Stack canary
* NX
* PIE/ASLR
* Stripped RPATH AND RUNPATH
* Stripped Symbols
* Fortify
The musl variants currently [do not support Fortify](https://wiki.musl-libc.org/future-ideas.html#Fortify).

feat: hardened authelia binaries

---

.buildkite/hooks/post-checkout
cmd/authelia-scripts/cmd_build.go
web/.cracorc.js
web/package.json
web/tsconfig.json
web/yarn.lock

This PR allows us to utilise [esbuild](https://esbuild.github.io/) for compilation and bundling as opposed to babel and terser respectively.
This allows faster builds both during production bundling and during development.

feat(web): replace babel-loader and terser with esbuild

---

config.template.yml
internal/configuration/config.template.yml

Tiny PR to fix a broken link to the SameSite cookie documention in the comments of config.template.yml

docs: fix broken url in config.template.yml

---

.github/commit-msg
docs/configuration/notifier/smtp.md

docs: fix required flag for smtp notifier sender option

---

internal/handlers/handler_oidc_wellknown.go
internal/oidc/types.go

Hello,
I've got a pretty trivial change which I couldn't test locally, so I'm going to rely on CI to tell me about build failures :) 
This adds the already existing token introspection endpoint to the openid-configuration file.

feat(oidc): include introspection_endpoint in .well-known/openid-configuration

---

docs/community/oidc-integrations.md

Add Hashicorp Vault oidc callback URLs and update tested version of MinIO in community docs.
Closes #2310.

docs: add hashicorp vault oidc configuration and update minio tested version

---

internal/authentication/const.go
internal/authentication/password_hash.go
internal/authentication/password_hash_test.go
internal/notification/smtp_notifier.go
internal/server/template.go
internal/session/const.go
internal/session/provider_config.go
internal/utils/const.go
internal/utils/hashing_test.go
internal/utils/strings.go
internal/utils/strings_test.go

This adjusts the session ID generator making it use it's own random function rather than using one from the utils lib. This allows us to utilize crypto/rand or math/rand interchangeably. Additionally refactor the utils.RandomString func to be safe for usage in goroutines.

fix(session): use crypto/rand for session id generator

---

internal/storage/migrations/V0001.Initial_Schema.mysql.up.sql
internal/storage/migrations/V0001.Initial_Schema.postgres.up.sql
internal/storage/migrations/V0001.Initial_Schema.sqlite.up.sql

This is a fix to the authentication_logs schema that prevents the VARCHAR from being insufficient for HTTP request methods such as PATCH, DELETE, OPTIONS, CONNECT.

fix(storage): new auth log schema request method length

---

internal/handlers/handler_register_u2f_step2.go
internal/storage/sql_provider.go
internal/storage/sql_provider_backend_postgres.go
internal/storage/sql_provider_queries.go

This replaces the standard duo_devices upsert with a PostgreSQL specific one and ensures the u2f_devices upsert uses the new unique key for the ON CONFLICT check.

fix(storage): duo/u2f upsert failure on postgresql

---

internal/configuration/schema/storage.go
internal/configuration/validator/storage.go
internal/configuration/validator/storage_test.go
internal/storage/sql_provider.go
internal/storage/sql_provider_backend_postgres.go
internal/storage/sql_provider_queries.go
internal/storage/sql_provider_schema.go

This removes the hardcoded schema value from the PostgreSQL existing tables query, making it compatible with the new schema config option.

fix(storage): postgres schema hardcoded for tables query

---

internal/models/types.go
internal/storage/sql_provider.go
internal/storage/sql_provider_backend_postgres.go
internal/storage/sql_provider_queries.go

This is already checked by JWT validation. There is no need and it's leading to timezone issues.
Fixes #2672

fix(storage): don't check exp against time using sql

---

internal/handlers/handler_register_u2f_step1_test.go
internal/middlewares/identity_verification.go
internal/middlewares/identity_verification_test.go
internal/models/identity_verification.go
internal/storage/sql_provider_encryption.go

This ensures that at the time the JWT is generated for identity verification requests that a panic can't occur and instead an error will be returned.

fix(models): potential panic generating jwt

---

.buildkite/steps/debhelper.sh

Due to changes upstream with makedeb the architecture is now deteremined through a query of `uname -m` this was causing the armhf build for the Debian package to fail.
We now provide the specific architecture that is detected to resolve the issue.

ci(buildkite): use armv7l architecture and ignore check

---

docs/configuration/identity-providers/oidc.md
internal/handlers/response.go

Adds the client id to a log message where it's likely useful. Additionally adds beta stage for prompt/display handling.

refactor(oidc): add client id to two factor log message

---

internal/handlers/handler_register_u2f_step1_test.go
internal/handlers/handler_sign_u2f_step1_test.go
internal/handlers/handler_verify_test.go
internal/middlewares/authelia_context.go
internal/middlewares/authelia_context_test.go
internal/middlewares/const.go
internal/middlewares/identity_verification_test.go
internal/middlewares/strip_path.go
internal/server/server.go
internal/server/template.go

This unifies the methods to obtain the X-Forwarded-* header values and provides logical fallbacks. In addition, so we can ensure this functionality extends to the templated files we've converted the ServeTemplatedFile method into a function that operates as a middlewares.RequestHandler.

fix(server): use of inconsistent methods for determining origin

---

.dockerignore
Dockerfile.dev
bootstrap.sh

This change ensures that BUILDKIT is enabled to pick up the correct Dockerfile and .dockerignore files during the build process of the dev image.
Fixes #2843. Closes #2844.

fix(docker): fix bootstrap and dev docker image build

---

docs/configuration/miscellaneous.md

Removes the gender specific examples for `default_redirection_url`, just seems a bit weird. 
As it's describing a general user example, having a specific gender, just reads a bit strange.

Update miscellaneous.md and default_redirect_url description

---

docs/configuration/identity-providers/oidc.md
internal/handlers/oidc.go
internal/handlers/oidc_test.go

This corrects an issue with the preferred_username which should be part of the profile scope as per https://openid.net/specs/openid-connect-core-1_0.html#ScopeClaims.
Introduced in ddbb21a via #2829

fix(oidc): make preferred_username a profile scope claim

---

internal/commands/storage.go
internal/commands/validate.go

Adjusts the default filename for all configuration files to configuration.yml.
Fixes #2939.

fix(commands): use consistent config file name

---

internal/handlers/oidc_register.go
internal/middlewares/const.go
internal/middlewares/cors.go
internal/middlewares/cors_test.go

This adds a Cross Origin Resource Sharing policy that automatically allows any cross-origin request to the OpenID Connect discovery documents.

feat(oidc): add automatic allow all cors to discovery

---

internal/configuration/validator/const.go

This fixes a bug that prevents the PKCE configuration keys from being configurable.

fix(configuration): pkce config keys not allowed

---

internal/configuration/decode_hooks.go
internal/configuration/decode_hooks_test.go

This fixes a potential panic in the time duration decode hook when the YAML value is a zero integer.
Fixes #2959

fix(configuration): time duration decode hook panic

---

docs/configuration/access-control.md

This adjusts a misleading configuration example.
Fixes #2770

docs: fix misleading config

---

internal/configuration/schema/authentication.go

This fixes a configuration parsing issue that could potentially occur if we were to change the internal name of the struct field.

fix(configuration): invalid password algorithm tag

---

.buildkite/steps/debhelper.sh

This adds the adjustments needed for the new `makedeb` version to package conffiles.
Fixes #2817

build: utilize new makedeb spec

---

docs/configuration/identity-providers/oidc.md

OIDC groups claim actually contains the user's groups, not the user's display name.

fix(docs): oidc group claim description incorrect

---

internal/handlers/handler_oidc_userinfo.go
internal/middlewares/identity_verification.go
internal/storage/sql_provider_encryption.go

This fixes a usage of uuid.New() which can potentially panic. Instead we use a uuid.NewRandom() which also generates a UUID V4 instead of a UUID V1. In addition all uuid.NewUUID() calls have been replaced by uuid.NewRandom().

fix(oidc): userinfo jti claim potential panic

---

internal/configuration/decode_hooks.go
internal/configuration/decode_hooks_test.go
internal/configuration/provider.go

This adds a hook func for url.URL and *url.URL types to the configuration.

refactor: include url hook func

---

internal/configuration/validator/const.go

This fixes an issue where the sentinel_username is not configurable.

fix(configuration): missing sentinel_username key in validator

---

internal/commands/storage_run.go

This fixes an issue that could potentially cause problems with open files due to a deferred file close in a for loop.

fix(commands): explicitly close files

---

internal/server/server.go
internal/server/template.go

This fixes an issue with the healthcheck writting the IPv6 host without brackets.
Fixes #3050

fix(server): healthcheck ipv6 format is invalid

---

internal/configuration/schema/server.go

This fixes the configuration mapping of the server enable_pprof and enable_expvars values.

fix(configuration): expvars and pprof mapped incorrectly

---

.buildkite/hooks/pre-exit

Occasionally due to node issues the pre-exit hook for docker image cleanups can fail, causing the otherwise successful job to bail out. This change ignores the cleanup on setup steps.

ci(buildkite): prevent pre-exit hook on setup steps

---

docs/community/oidc-integrations.md

Was looking to add another OIDC application entry, but noticed the Currently Tested Applications table isn't being rendered correctly by Just the Docs and could use adjusting first.
This change moves the 'MinIO policies' link from the footer into the applicable row and shifts the closing pipe up one line.

docs: fix oidc applications table display

---

docs/community/oidc-integrations.md

Tested working Miniflux feed reader OIDC settings.
Miniflux added generic OpenID Connect provider support in version 2.0.21 [(PR#583)](https://github.com/miniflux/v2/pull/583).
Tried to keep table markup aligned with existing entries but it does get a bit messy.

docs: add oidc details for miniflux app

---

config.template.yml
docs/configuration/password_policy.md
docs/features/password-policy.md
internal/commands/helpers.go
internal/configuration/config.template.yml
internal/configuration/schema/configuration.go
internal/handlers/errors.go
internal/handlers/handler_reset_password_step2.go
internal/middlewares/const.go
internal/middlewares/password_policy.go
internal/middlewares/password_policy_test.go
internal/middlewares/types.go
internal/suites/Standalone/configuration.yml
web/package.json
web/pnpm-lock.yaml

Add tests and makes the password policy a provider so the configuration can be loaded to memory on startup.

refactor: misc password policy refactoring

---

web/src/index.tsx

This PR utilises the React 18 Client Rendering API along with createRoot as opposed to the React 17 ReactDOM.render method.

fix(web): update client rendering method

---

docs/configuration/identity-providers/oidc.md
docs/roadmap/oidc.md

This is a meta commit documenting the change from using the username as a subject identifier to a specification compliant subject identifier in the form of RFC4122 https://datatracker.ietf.org/doc/html/rfc4122 UUID V4 subject identifiers. This is a required change in order to be compliant with the specification as per https://openid.net/specs/openid-connect-core-1_0.html#SubjectIDTypes. Relying parties which utilize the subject identifier / sub claim may need manual intervention in order to relink accounts. Users who have issues will have to consult with the documentation of their individual relying parties in order to relink accounts. Users who utilized the subject identifier as a means to provision their users are also encouraged to utilize the preferred_username claim from the profile …

feat(oidc): opaque subject identifiers

---

internal/server/locales/en/portal.json
web/src/components/TypographyWithTooltip.test.tsx
web/src/components/TypographyWithTootip.tsx
web/src/hooks/UserInfo.ts
web/src/layouts/LoginLayout.tsx
web/src/services/UserInfo.ts
web/src/views/LoginPortal/ConsentView/ConsentView.tsx

This adds the current logged in users display name to the consent page as well as some other minor tweaks.
Closes #2595

feat(web): add user display name to oidc consent view

---

internal/handlers/handler_checks_safe_redirection.go
internal/handlers/handler_checks_safe_redirection_test.go
internal/handlers/handler_configuration.go
internal/handlers/handler_configuration_test.go
internal/handlers/handler_firstfactor.go
internal/handlers/handler_firstfactor_test.go
internal/handlers/handler_health.go
internal/handlers/handler_logout.go
internal/handlers/handler_logout_test.go
internal/handlers/handler_register_duo_device.go
internal/handlers/handler_register_duo_device_test.go
internal/handlers/handler_register_totp.go
internal/handlers/handler_register_webauthn.go
internal/handlers/handler_reset_password_step2.go
internal/handlers/handler_sign_duo.go
internal/handlers/handler_sign_duo_test.go
internal/handlers/handler_sign_totp.go
internal/handlers/handler_sign_totp_test.go
internal/handlers/handler_sign_webauthn.go
internal/handlers/handler_state.go
internal/handlers/handler_state_test.go
internal/handlers/handler_user_info.go
internal/handlers/handler_user_info_test.go
internal/handlers/handler_user_totp.go
internal/handlers/handler_verify.go
internal/handlers/handler_verify_test.go
internal/middlewares/require_first_factor.go
internal/server/handlers.go
internal/server/server.go

This fixes edge cases where the remote IP was not correctly logged. Generally this is not an issue as most errors do not hit this handler, but in instances where a transport error occurs this is important.

fix(server): incorrect remote ip logged in error handler

---

docs/configuration/server.md
internal/server/server.go
web/src/i18n/index.ts

This fixes an issue with localization platforms and the docs regarding localization, and the forcing locale names to lowercase.

 fix(web): locales are not consistent with localization platforms

---

internal/configuration/validator/identity_providers.go
internal/configuration/validator/identity_providers_test.go
internal/utils/strings.go
internal/utils/strings_test.go

This fixes an issue preventing the sector identifier for OpenID Connect clients from being parsed.

fix(configuration): sector identifier not parsed correctly

---

internal/server/locales/de/portal.json
internal/server/locales/en/portal.json
internal/server/locales/es/portal.json
web/src/views/LoginPortal/ConsentView/ConsentView.tsx

This adjusts the profile scope to be described as "Access your profile information" as it accesses more than the display name now.

fix(web): description of profile scope is not accurate

---

api/openapi.yml
config.template.yml
internal/configuration/config.template.yml
internal/configuration/schema/password_policy.go
internal/configuration/validator/const.go
internal/configuration/validator/keys.go
internal/configuration/validator/keys_test.go
internal/configuration/validator/password_policy.go
internal/configuration/validator/password_policy_test.go
internal/handlers/handler_configuration_password_policy.go
internal/handlers/types.go
internal/middlewares/password_policy_test.go
web/src/components/PasswordMeter.test.tsx
web/src/models/PasswordPolicy.ts
web/src/services/PasswordPolicyConfiguration.ts
web/src/views/ResetPassword/ResetPasswordStep2.tsx

Removes the min score option from the ZXCVBN policy and adds tests.

fix(configuration): remove unused password policy option

---

internal/oidc/discovery.go
internal/oidc/provider_test.go

This adds the AMR claim to discovery.

fix(oidc): missing amr claim supported in discovery

---

internal/server/asset.go

This fixes an issue where the locale would be formatted as en-en instead of en-US.

fix(server): locale format incorrect

---

internal/suites/example/compose/authelia/docker-compose.backend.dev.yml
internal/suites/example/compose/authelia/docker-compose.backend.dist.yml

This change includes missing routes for both the Traefik and Traefik2 suites, issues would have manifested running dev mode tests for these suites when attempting to load translations.

fix(suites): add missing traefik routes

---

.buildkite/steps/debhelper.sh

makedeb v14.0.0 has [changes](https://github.com/makedeb/makedeb/releases/tag/v14.0.0-stable) which have resulted in the PKGBUILD specification changing.
This PR adjusts the PKGBUILD per the required makedeb specification.

ci(buildkite): adjust debhelper step for new makedeb spec

---

.buildkite/steps/e2etests.sh
cmd/authelia-scripts/cmd_suites.go
internal/suites/example/compose/authelia/docker-compose.backend.dev.yml
internal/suites/example/compose/authelia/docker-compose.backend.dist.yml
internal/suites/example/compose/authelia/docker-compose.frontend.dev.yml
internal/suites/example/compose/authelia/docker-compose.frontend.dist.yml
internal/suites/example/compose/haproxy/haproxy.cfg
internal/suites/example/compose/httpbin/docker-compose.yml
internal/suites/example/compose/nginx/backend/docker-compose.yml
internal/suites/example/compose/oidc-client/docker-compose.yml
internal/suites/example/compose/smtp/docker-compose.yml
internal/suites/example/compose/traefik2/docker-compose.yml
internal/suites/suite_haproxy.go
internal/suites/suite_oidc_traefik.go
internal/suites/suite_pathprefix.go
internal/suites/suite_traefik.go
internal/suites/suite_traefik2.go
internal/suites/suite_traefik2_test.go

This PR adds the ability to pass the `--failfast` option to the `suites test` command in order to fail a suite on initial test failure. It also has taken the liberty to remove the `authelia-frontend` nginx container which acts as a secondary proxy in dist/CI testing simplifying the overall solution.

refactor(suites): stop integration tests on first failure

---

internal/middlewares/asset_override.go
internal/middlewares/const.go
internal/middlewares/headers.go
internal/middlewares/log_request.go
internal/middlewares/log_request_test.go
internal/middlewares/strip_path.go
internal/server/handlers.go

This fixes an issue with missing modern security headers such as the X-Content-Type-Options, Referer-Policy, etc.

fix(server): missing modern security headers

---

README.md

A bit of a followup to #3307. This directly mentions caddy for easier `CTRL`+`F` skimming of the readme.

docs: add caddy to readme.md

---

docs/configuration/storage/mariadb.md
docs/configuration/storage/mysql.md
docs/configuration/storage/postgres.md
docs/configuration/storage/sqlite.md
docs/deployment/supported-proxies/caddy.md

This adds supported version / configuration info to primarily MySQL/MariaDB.
Closes #2822

docs: add sql supported version info

---

docs/configuration/authentication/file.md

Was reading through the docs and realised there's a missing format character when mentioning the SHA512 algorithm under password (https://www.authelia.com/docs/configuration/authentication/file.html#algorithm).
This minor PR fixes the mentioned typo.

docs: fix missing backtick in file authentication docs

---

internal/authentication/ldap_user_provider.go
internal/authentication/ldap_user_provider_startup.go
internal/authentication/ldap_user_provider_test.go

This fixes an issue when both the username and display name attributes are the same. If the username attribute is the same as the display name attribute previously we only set the display name profile value which is incorrect. We should set the username profile value instead and allow the display name to be blank.
Fixes #3359

fix(authentication): err when user/display name same ldap attribute

---

README.md

Adds a link to caddys documentation for `forward_auth`

Link to caddy forward_auth docs

---

web/src/App.test.tsx
web/src/components/AppStoreBadges.test.tsx
web/src/components/ColoredSnackbarContent.test.tsx
web/src/components/PasswordMeter.test.tsx
web/src/components/PasswordMeter.tsx

This change drops the use of ReactDOM which is not supported in React 18. We also fix any test warnings related to i18next.

test(web): fix tests to conform to react18

---

internal/server/handlers.go
internal/server/server.go

This fixes an issue where errors handled by the ErrorHandler were not correctly logged. It also ensures the errors are logged with fields to make them easy to diagnose.
Fixes #3506

fix(server): handled errors not logged correctly

---

internal/handlers/handler_oidc_token.go
internal/model/oidc.go

This fixes a potential panic in the conversion from a fosite.Requester to an *OAuth2Session object.

fix(model): potential panic

---

internal/suites/example/compose/caddy/Caddyfile
internal/suites/example/compose/caddy/Dockerfile
internal/suites/example/compose/caddy/docker-compose.yml
internal/suites/example/compose/nginx/portal/nginx.conf
internal/suites/verify_body_contains.go

This change fixes an issue that was incorrectly marking the primary load balancer target for the front end in dev mode as down.

fix(suites): fix passive health checks for caddy suite

---

docs/content/en/integration/openid-connect/argocd/index.md
internal/commands/acl.go

This fixes an issue with the authelia access-control check-policy command which potentially panics when a decode hook fails to parse an item.

fix(commands): acl check panic on decode failure

---

internal/authorization/authorizer_test.go
internal/utils/const.go
internal/utils/url.go
internal/utils/url_test.go

This fixes an issue with the URL matching machinery which ignores the final slash of a URL. Introduced in 664d65d7fb4cd77f66629dc42c0a2c4a3ccc36a4.
Fixes #3692

fix(authorization): final slash in url matches ignored

---

docs/content/en/contributing/prologue/introduction.md

docs: fix contributing introduction link

---

docs/content/en/integration/openid-connect/grafana/index.md

When integrating Grafana with Authelia I encountered a problem where Grafana wasn't passing Authelia the correct redirect uri resulting in the following error.
`The 'redirect_uri' parameter does not match any of the OAuth 2.0 Client's pre-registered redirect urls`
Making the following change to my grafana.ini config fixed the issue for me.

Grafana Integration Doc Changes

---

web/.eslintrc.js
web/src/App.tsx
web/src/components/NotificationBar.tsx
web/src/components/TimerIcon.tsx
web/src/hooks/IntermittentClass.ts
web/src/hooks/Mounted.ts
web/src/hooks/RemoteCall.ts
web/src/hooks/Timer.ts
web/src/layouts/LoginLayout.tsx
web/src/services/Configuration.ts
web/src/services/Consent.ts
web/src/services/PushNotification.ts
web/src/services/RegisterDevice.ts
web/src/services/ResetPassword.ts
web/src/views/DeviceRegistration/RegisterOneTimePassword.tsx
web/src/views/LoginPortal/AuthenticatedView/AuthenticatedView.tsx
web/src/views/LoginPortal/ConsentView/ConsentView.tsx
web/src/views/LoginPortal/FirstFactor/FirstFactorForm.tsx
web/src/views/LoginPortal/SecondFactor/DeviceSelectionContainer.tsx
web/src/views/LoginPortal/SecondFactor/MethodContainer.tsx
web/src/views/LoginPortal/SecondFactor/MethodSelectionDialog.tsx
web/src/views/LoginPortal/SecondFactor/PushNotificationMethod.tsx
web/src/views/LoginPortal/SecondFactor/SecondFactorForm.tsx
web/src/views/LoginPortal/SignOut/SignOut.tsx
web/src/views/ResetPassword/ResetPasswordStep1.tsx

The [ignoreDeclarationSort](https://eslint.org/docs/latest/rules/sort-imports#ignoredeclarationsort) and [memberSyntaxSortOrder](https://eslint.org/docs/latest/rules/sort-imports#membersyntaxsortorder) options have been turned on and omitted respective to not conflict with the existing import/order rules.

ci: add eslint rule for sorting imports

---

docs/content/en/roadmap/active/webauthn.md

Prevents communicating a misleading deprecation of WebAuthn, when it's actually referring to the (_now legacy_) U2F API that Chrome is dropping (_and has already removed_).
---
**Side-note:**
Your CI reacted to a minor update to docs and looks like it's running the whole suite of jobs that has nothing to do with docs.

docs: Clarify that Chrome did not deprecate WebAuthn

---

internal/authorization/authorizer.go
internal/authorization/authorizer_test.go
internal/handlers/handler_verify.go
internal/handlers/handler_verify_test.go
internal/handlers/response.go

When an anonymous user tries to access a forbidden resource
with no subject, we should response with 403.
Fixes #3084

fix(handlers): fix forbidden acl for anonymous user

---

web/src/components/PasswordMeter.tsx

This adjusts the special character regex to consider all characters which are not alphanumeric as special, including the underscore.

refactor(web): adjust special char regex

---

config.template.yml
internal/configuration/config.template.yml
internal/storage/const.go
internal/storage/sql_provider_backend_mysql.go

The timestamps in MySQL were not being parsed correctly. The driver treats all timestamp and datetime objects the same which is not correct.

fix(storage): mysql timestamp parsed incorrectly

---

docs/content/en/integration/proxies/fowarded-headers/index.md

There were minor typos, and a phrase with no ending, I only fixed that.

Minor fixes in "Forwarded Headers" documentation

---

internal/storage/migrations/V0006.ConsentPreConfiguration.mysql.up.sql
internal/storage/migrations/V0006.ConsentPreConfiguration.postgres.up.sql
internal/storage/migrations/V0006.ConsentPreConfiguration.sqlite.up.sql
internal/storage/sql_provider_backend_postgres.go

This fixes a typo with the default port for PostgreSQL in 4.37.
Fixes #4249

fix(storage): postgresql default port incorrect

---

internal/authentication/ldap_user_provider.go
internal/authentication/ldap_user_provider_startup.go
internal/authentication/ldap_user_provider_test.go

The BaseDN for groups was escaped improperly and failed on any BaseDN with special characters. This fixes the issue. Introduced in a3b14871baeca9ebfbaded981bebb6f9c36b0311 (v4.30.0).
Fixes #4274

fix(authentication): erroneously escaped group base dn

---

docs/content/en/reference/cli/authelia/authelia_crypto_hash_generate.md
docs/content/en/reference/cli/authelia/authelia_crypto_hash_generate_argon2.md
docs/content/en/reference/cli/authelia/authelia_crypto_hash_generate_bcrypt.md
docs/content/en/reference/cli/authelia/authelia_crypto_hash_generate_pbkdf2.md
docs/content/en/reference/cli/authelia/authelia_crypto_hash_generate_scrypt.md
docs/content/en/reference/cli/authelia/authelia_crypto_hash_generate_sha2crypt.md
docs/content/en/reference/cli/authelia/authelia_crypto_rand.md
internal/commands/const.go
internal/commands/crypto.go
internal/commands/crypto_hash.go
internal/commands/util.go
internal/utils/const.go

This includes the RFC3986 unreserved charset as an option, and allows the '-upper' and '-lower' suffix for alphabetic inclusive charsets.

refactor(commands): include rfc3986 charset

---

cmd/authelia-scripts/cmd/docker.go
cmd/authelia-scripts/cmd/helpers_docker.go

#4071 introduced a regression where Docker manifest hashes did not match between the same semantic versions, this is due to the `org.opencontainers.image.created` label/annotation. We now perform a single build and push to remedy this issue.
Fixes #4353, Closes #4351.

ci: fix docker tag manifest hashes

---

api/openapi.yml
internal/handlers/handler_register_webauthn.go
web/src/services/Webauthn.ts
web/src/views/DeviceRegistration/RegisterWebauthn.tsx

WebAuthn devices are currently registered with the constant name `Primary`. In preparing for multiple WebAuthn device support, this value will eventually need to be a user-entered name.
This PR provides the first step by moving the constant `Primary` from the backend to the frontend. This updates the WebAuthn attestation API endpoint to accept the description string value from the client request.
This is part of the work for https://github.com/authelia/authelia/issues/4366.

feat: provide webauthn device description from frontend on registration

---

cmd/authelia-scripts/cmd/bootstrap.go

This change prevents installing the `node_modules` on CI nodes that do not require them.

refactor(cmd): restrict bootstrap pnpm tasks to dev environment

---

web/src/views/Settings/SettingsView.tsx

fix: add toolbar below appbar in settings page to avoid content overlap

---

internal/configuration/validator/const.go
internal/configuration/validator/identity_providers.go
internal/configuration/validator/identity_providers_test.go

This fixes an issue where redirect URIs which may be valid are rejected by the configuration validator. This will instead allow the OpenID Connect 1.0 flows to validate them individually.

fix(configuration): valid oidc redirect uris not accepted

---

web/.eslintrc.js
web/package.json
web/pnpm-lock.yaml

This linter utilises alias/path configuration specified in the `tsconfig.json` for imports, this allows us to enforce consistency within the frontend codebase.

ci(web): add eslint alias linter

---

docs/content/en/configuration/storage/postgres.md

Corrected spelling of "postgres" in server config example.

Docs: spelling correction

---

docs/content/en/overview/security/measures.md

Adds password reset/email spam filter in fail2ban docs.
I've only tested these fail2ban rules with totp 2fa device resets, not sure if it catches others.

Add password reset/email spam filter in fail2ban docs.

---

internal/commands/util_test.go
internal/configuration/provider_test.go
internal/templates/funcs_test.go

A testing cleanup.
This PR replaces `os.Setenv` with `t.Setenv`. Starting from Go 1.17, we can use `t.Setenv` to set environment variable in test. The environment variable is automatically restored to its original value when the test and all its subtests complete. This ensures that each test does not start with leftover environment variables from previous completed tests.
This saves us at least 2 lines (error check, and cleanup) on every instance.
Reference: https://pkg.go.dev/testing#T.Setenv
```go
func TestFoo(t *testing.T) {
// before
os.Setenv(key, "new value")
defer os.Unsetenv(key)
// after
t.Setenv(key, "new value")
}
```

test: use `T.Setenv` to set env vars in tests

---

internal/notification/smtp_auth.go
internal/notification/smtp_notifier.go

This fixes an issue introduced by the pending migration to the new SMTP library in 0bb657e11cfa6b9f16cd28340291b121fa1579bc where the auth mechanism is never defined. This only affects commits that are yet to be versioned.

fix(notification): smtp auth not configured

---

web/src/views/LoginPortal/SecondFactor/OTPDial.tsx

This sets the autocomplete value to `one-time-code` instead of using the default of `off`.
Fixes #4660

fix:(web): otp autocomplete defaults to off

---

docs/content/en/integration/proxies/swag.md

Updated SWAG Reverse Proxy documentation to map to the same directory using a docker bind mount of swag (/config) to allow the commands to be used without manual directory moving / updating after creating each file.

Fix Directory structure in SWAG Documentation

---

internal/suites/environment.go

After PR #4751 the suites times out if takes more of 60 seconds.
This PR honors the timeout configured at waitUntilAutheliaBackendIsReady (90s)

fix(utils): fix suite setup timeout

---

.renovaterc

This fixes an issue with a trailing comma in the .renovaterc file.
Fixes #3293

ci: fix renovaterc

---

docs/content/en/integration/proxies/caddy.md
docs/content/en/integration/proxies/haproxy.md
docs/content/en/integration/proxies/traefik.md
docs/content/en/integration/proxies/traefikv1.md

This PR fixes some IP address ranges which I assume were meant to be a list of all [private IP address ranges](https://en.wikipedia.org/wiki/Private_network#Private_IPv4_addresses) but were specifying 172.16.0.0/16 instead of 172.16.0.0/12.

docs: fix ip addresses

---

docs/content/en/reference/guides/generating-secure-values.md

"the" is written both at the end of line 22 and the start of line 23 which results in
> the the string

docs: fix typo

---

docs/content/en/integration/openid-connect/gitea/index.md

Make the non-obvious relationship between the Gitea `Authentication Name` and the path of the redirect URI explicit.

docs: Note importance of name in gitea config

---

internal/suites/example/compose/haproxy/Dockerfile
internal/suites/example/compose/haproxy/docker-compose.yml
internal/suites/example/compose/haproxy/haproxy.cfg

This utilises the certs provided within the pki section of the repo for the HAProxy suite.

refactor(suites): utilise pki certs in haproxy suite

---

internal/handlers/handler_authz.go
internal/handlers/handler_authz_impl_legacy_test.go

Since nginx doesn't do portal URL detection we have to skip returning an error on the legacy authz implementation when the portal URL isn't detected.

fix(handlers): legacy authz failure on nginx

---

internal/commands/const.go
internal/commands/services.go
internal/suites/environment.go

This fixes a race condition which in some circumstances (seemed to only affect a deliberately under provisioned VM in testing, however it could still theoretically occur on any system) can cause the process to hang during a shutdown. While unrelated this also adds additional trace logging to the shutdown process to better capture each stage to better facilitate debugging in the future specifically when one particular service is taking time to stop.
Fixes #4963

fix(commands): internal services not cleaned up properly

---

internal/suites/example/compose/authelia/docker-compose.frontend.dev.yml
web/.env.production
web/index.html
web/vite.config.ts

#5073 introduced native env replacement within Vite therefore we can remove our html-transform hook.

refactor(web): native vite env replacement

---

.buildkite/hooks/post-artifact
.buildkite/hooks/pre-artifact
.buildkite/hooks/pre-command

This change ensures that vega Buildkite nodes will upload artifacts to a local MinIO instance and also retrieve artifacts from this location if the same constraint is met.

ci(buildkite): localised node artifacts

---

internal/configuration/deprecation.go

When `host` is set at the top level of configuration, we get as a result a misleading warn about its deprecation :
level=warning msg="Configuration: configuration key 'logs_file' is deprecated in 4.30.0 and has been replaced by 'server.host': this has been automatically mapped for you but you will need to adjust your configuration to remove this message"

fix(configuration): misleading warning about logs_file

---

internal/commands/util.go
internal/commands/util_test.go

This fixes an issue where if the implicit config location of configuration.yml does not exist that an error is returned. This does not affect the behaviour when the method was either implicit or environment.

fix(commands): storage cmd fail when implicit config absent

---

internal/commands/crypto_hash.go

This fixes an issue where the authelia crypto hash generate command does not automatically error when used with arguments leading to some confusing output.

fix(commands): crypto hash gen missing no args

---

docs/content/en/reference/guides/branding.md

This just syncs the master branches branding docs from the live website as the master branch was out of date (the live website was not).

docs: sync branding docs with live

---

docs/content/en/reference/cli/authelia/authelia_crypto_certificate_ecdsa_generate.md
docs/content/en/reference/cli/authelia/authelia_crypto_certificate_ecdsa_request.md
docs/content/en/reference/cli/authelia/authelia_crypto_certificate_ed25519_generate.md
docs/content/en/reference/cli/authelia/authelia_crypto_certificate_ed25519_request.md
docs/content/en/reference/cli/authelia/authelia_crypto_certificate_rsa_generate.md
docs/content/en/reference/cli/authelia/authelia_crypto_certificate_rsa_request.md
internal/commands/crypto.go
internal/commands/crypto_helper.go

Several crypto generate situations could not generate PKCS #8 ASN.1 DER format keys. Ths fixes this.

fix(commands): missing pkcs8 option

---

internal/middlewares/authelia_context.go
internal/middlewares/authelia_context_test.go

This fixes an edge case where the RemoteIP detection could safely fail with an error, and instead defaults to the TCP packet information.

fix(middlewares): failure to detect remote ip

---

docs/content/en/configuration/identity-providers/openid-connect/provider.md
internal/configuration/validator/const.go
internal/configuration/validator/identity_providers.go
internal/configuration/validator/identity_providers_test.go

This allows disabling the minimum parameter entropy checks.

feat(oidc): disable minimum parameter entropy

---

.github/ISSUE_TEMPLATE/bug-report.yml
cmd/authelia-gen/templates/github_issue_template_bug_report.yml.tmpl
cmd/authelia-scripts/cmd/gen.go
internal/notification/smtp_notifier.go

This fixes an issue where the mime multipart parts were in the incorrect order. Only affects beta releases.
Fixes #5617

fix(notifier): mime parts in reverse order

---

docs/content/en/configuration/miscellaneous/ntp.md
internal/commands/const.go
internal/commands/root.go

The NTP startup check is helpful for identifying not only TOTP issues but also OpenID Connect 1.0 and Session issues. As such it should be performed even if 2FA is disabled. This fixes this issue.

fix(ntp): startup check skipped when it shouldn't be

---

.buildkite/hooks/post-artifact
.buildkite/hooks/pre-command

This change ensures that aquilla Buildkite nodes will upload artifacts to a local MinIO instance and also retrieve artifacts from this location if the same constraint is met.

ci(buildkite): additional localised node artifacts

---

internal/oidc/config.go
internal/oidc/const.go
internal/oidc/const_test.go
internal/oidc/pkce.go
internal/oidc/pkce_test.go
internal/oidc/types_test.go

This handles an issue where the PKCE sessions were generated needlessly which also resulted in an unexpected error in rare circumstances.

fix(oidc): pkce session generated needlessly

---

internal/metrics/metrics.go
internal/metrics/prometheus.go
internal/middlewares/metrics.go
internal/server/handlers.go

This adds a histogram vector on a per-endpoint basis for OpenID Connect 1.0 which records the elapsed seconds by endpoint by code.

feat(metrics): record openid connect histogram

---

internal/handlers/handler_oauth_introspection.go
internal/handlers/handler_oauth_revocation.go
internal/handlers/handler_oidc_userinfo.go

This fixes an issue where on the userinfo, introspection, and revocation endpoints there are not sufficient logs at the debug level to see the flow of a the request.

fix(oidc): insufficient debug logs on some endpoints

---

.buildkite/hooks/post-artifact
.buildkite/hooks/pre-command

This change factorizes node configuration to ensure that all nodes within a singular network upload artifacts once and are accessible across the board.

ci(buildkite): factorize minio node configuration

---

.github/workflows/codeql-analysis.yml

This replaces deprecated actions from within our workflows per feedback [here](https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/).

ci: update code-ql actions

---

examples/compose/local/README.md

There was a missing readme and missing context to the readme for the example bundles. This resolves this.

docs: expand on existing bundle info

---

internal/configuration/validator/access_control.go

From the Go docs:
> "For a nil slice, the number of iterations is 0." https://go.dev/ref/spec#For_range
Therefore, an additional nil check for before the loop is unnecessary. Example: https://go.dev/play/p/2TugLncT_ob

refactor(validator): remove redundant nil check

---

internal/model/oidc.go

This fixes an initial implementation issue where the PAR context was not mapped correctly.

fix(oidc): par model mapping

---

internal/handlers/webauthn.go
internal/handlers/webauthn_test.go
web/src/models/WebAuthn.ts
web/src/services/WebAuthn.ts

Browsers have seemingly changed the requirements for registering credentials which now requires user.id property. It is unclear from the discussions in the working group if this was intended as there are conflicting discussions.

fix: webauthn credential user id missing

---

web/.eslintrc.js
web/package.json
web/pnpm-lock.yaml
web/src/components/PrivacyPolicyDrawer.test.tsx
web/src/components/PrivacyPolicyLink.test.tsx
web/src/setupTests.ts
web/tsconfig.json
web/vite.config.ts

This change replaces the existing ESLint plugin which also provides capability to perform additional checking, including TypeScript.

ci(web): replace vite-plugin-eslint with vite-plugin-checker

---

internal/oidc/flow_refresh.go

This ensures if we add custom scope strategies later then we don't accidentally give clients more scopes than the resource owner granted.

refactor(oidc): use exact scope matching

---

internal/configuration/const.go
internal/configuration/helpers.go
internal/configuration/helpers_test.go
internal/configuration/sources.go

This fixes an issue where a deprecated configuration options when used as a secret are not mapped like the other configuration sources are.

fix(configuration): deprecated secrets not mapped

---

docs/content/en/configuration/methods/files.md
docs/content/en/reference/guides/templating.md
internal/configuration/koanf_provider_filtered_file.go
internal/configuration/provider_test.go
internal/configuration/test_resources/config.filtered.yml
internal/configuration/test_resources/example_password_secret
internal/templates/funcs.go

This shows an example of using a template filter to include a single line secret.

test: add example single line filter

---

cmd/authelia-scripts/cmd/gen.go
docs/content/en/configuration/first-factor/introduction.md
docs/data/configkeys.json
docs/static/schemas/latest/json-schema/configuration.json
docs/static/schemas/v4.38/json-schema/configuration.json
internal/configuration/decode_hooks.go
internal/configuration/decode_hooks_test.go
internal/configuration/provider.go
internal/configuration/provider_test.go
internal/configuration/schema/authentication.go
internal/configuration/schema/const.go
internal/configuration/schema/keys.go
internal/configuration/schema/types.go
internal/configuration/test_resources/config.durations.yml
internal/configuration/test_resources/config.no-refresh.yml
internal/configuration/test_resources/config.yml
internal/configuration/validator/authentication.go
internal/configuration/validator/authentication_test.go
internal/handlers/handler_authz_authn.go
internal/handlers/handler_authz_builder.go
internal/handlers/handler_authz_builder_test.go
internal/handlers/handler_authz_test.go
internal/handlers/handler_authz_types.go
internal/handlers/handler_firstfactor.go
internal/mocks/authelia_ctx.go

When using the file provider with watch enabled, the refresh interval should just be set to always by default as the cost is minimal.

fix(configuration): illogical refresh interval default

---

Dockerfile.coverage
Dockerfile.dev
internal/suites/example/compose/authelia/Dockerfile.backend

Temporary fix for https://github.com/mattn/go-sqlite3/pull/1177 which will be reverted in the near future as that's merged.

build: explicitly use alpine 3.18

---

internal/configuration/validator/session.go
internal/configuration/validator/session_test.go

This fixes an issue introduced in 5edd5fcf69d8f17a6731e0f1b5cf8f8591823e56 which prevented a redis socket from being used. The redis port zero value is used to determine if we should attempt to utilize a unix socket but the contribution always sets it as default regardless.

fix(configuration): regression in redis default port

---

internal/handlers/const.go
internal/handlers/handler_oidc_authorization_consent_pre_configured.go

This improves the pre-configured consent logging adding the audience and logging each failed match.

refactor(oidc): add pre-configured consent logs

---

internal/handlers/handler_oidc_authorization_consent.go
internal/handlers/handler_oidc_authorization_consent_pre_configured.go

This fixes an issue in master which prevented the audience from matching in pre-configured consent sessions.

fix(oidc): pre-config audience not matched

---

docs/content/en/integration/openid-connect/freshrss/index.md

Create integration guide for oidc authentication for freshrss and authelia
Document non-obvious behaviour that freshrss expects port in the redirect URI
Signed-off-by: darkpixelftw <darkpixelftw@outlook.com>

docs(oidc): add freshrss oidc integration guide

---

config.template.yml
internal/configuration/config.template.yml

This change ensures that our configuration templates align with the expected key names and documentation.
Fixes #6948.

fix(configuration): rename token_lifespan in configuration example

---

internal/authorization/authorizer.go
internal/authorization/authorizer_test.go
internal/authorization/util.go
internal/authorization/util_test.go

This fixes an issue where the MFA enabled state is not correctly detected if the only 'two_factor' policy configured was a custom OpenID Connect 1.0 policy. This ends up being a bad UX as admins have to configure a dummy 'two_factor' policy instead of it being automatically detected.
Fixes #7103.

fix(authorization): mfa not detected in custom policies

---

internal/logging/const.go
internal/logging/logger.go

This ensures the stacktrace is only included when the log level is configured above info, for example debug/trace.

refactor(logging): only include stacktrace above info

---

go.mod
go.sum
internal/configuration/decode_hooks.go
internal/configuration/schema/types.go
internal/configuration/validator/identity_providers.go
internal/oidc/config.go

A misconfigured client can potentially throw a nil panic which is recovered but undesirable. This fixes that issue.
Fixes #6933

fix(oidc): potential nil panic with misconfigured client

---

docs/content/integration/proxies/nginx.md

This makes the location /api/verify an exact location. This has no major effects but is a best practice.

docs: make nginx location exact

---

.buildkite/hooks/pre-command

This change ensures that if nodes that share artifacts through MinIO happen to error and are brought back up, they can finish builds that had the coverage step run by nodes that upload to Buildkites S3 instance.

ci(buildkite): adjust integration tests pre-command hook

---

docs/content/configuration/identity-providers/openid-connect/provider.md

Improve documentation clarity by adding "required" tag to OIDC provider field: clients.
It is intended behavior that there be at least one configured open id connect client in order for OIDC config to be valid.

docs: improve clarity - oidc client field is required

---

internal/commands/config.go
internal/suites/suite_cli_test.go

This fixes an issue where the exit status for the config validate command returns a 0 instead of 1.
Fixes #7262

fix(commands): validate exit status

---

docs/content/integration/openid-connect/introduction.md
internal/handlers/handler_sign_webauthn.go
internal/oidc/amr.go
internal/oidc/amr_test.go
internal/oidc/const.go
internal/session/provider_test.go
internal/session/user_session.go
internal/session/user_session_test.go

This includes the missing Authentication Method Reference named 'pop' or proof-of-possession, as well as properly distinguishing between the 'hwk' and 'swk' variants of WebAuthn.

fix(oidc): include missing amr with value pop

---

internal/handlers/handler_oidc_authorization_consent.go
internal/handlers/handler_oidc_authorization_consent_explicit.go
internal/handlers/handler_oidc_authorization_consent_implicit.go
internal/handlers/handler_oidc_authorization_consent_pre_configured.go
internal/model/uuid.go
internal/oidc/store_test.go

Instead of utilizing the ID of the UUID this compares it directly which was intentionally intended by the authors.

refactor: use explicit uuid comparison

---

internal/middlewares/const.go
internal/middlewares/cors.go
internal/middlewares/cors_test.go

The Allow header was set instead of the Cross-Origin Resource Sharing header Access-Control-Allow-Methods. This fixes that issue.

fix(middlewares): header allow set instead of acam

---

docs/layouts/shortcodes/config-alert-example.html
docs/layouts/shortcodes/confkey.html

This uses the modern callout design instead of alerts for in doc alerts.

docs: use modern callout instead of alert

---

docs/data/support.json

Tested Okta Verify for different TOTP options (since I was unable to get it to work when I first tried it).  Okta Verify only supports SHA1 with 6-digits.

Add support information for Okta Verify

---

web/src/views/Settings/TwoFactorAuthentication/OneTimePasswordPanel.tsx
web/src/views/Settings/TwoFactorAuthentication/WebAuthnCredentialsPanel.tsx

This fixes an issue where the UX was not great when adding new credentials with low feedback and the potential to double click the add button.

fix(web): average ux when adding credentials

---

.github/dependabot.yml

As we use renovate for all other packages this creates quite the overlap from the recommended configuration. Instead we just need to ensure dependabot handles the github actions elements.

ci: update dependabot

---

web/src/hooks/RelativeTimeString.ts
web/src/views/Settings/TwoFactorAuthentication/CredentialItem.tsx

The existing date format for creation time/last used time for 2fa methods in the user settings menu is a bit lengthy and doesn't render too well even on desktop devices. This changes it to a delta-time format. Instead of showing the date, it shows the time since the last event e.g. just now, one day ago, 2 years ago etc.
Creation time/last used time doesn't need to be very specific, having the exact date and time when a credential was created/used isn't a super big issue.
For webauthn credentials, users still have the ability to see the exact date and time by inspecting the credential.
I think this should increase the readability of the settings page while also cutting down on the clutter, while maintaining clarity on when credentials were created/used.

refactor web: change 2fa method created_at last_used time to time-since-date from formatted date

---

internal/templates/src/emails/Event.tsx
internal/templates/src/emails/IdentityVerificationJWT.tsx
internal/templates/src/emails/IdentityVerificationOTC.tsx

Apply some minor changes to the formatting and wording of the new email templates.
It should be noted that I think that we should be pretty specific what events we are talking about in the email. Rather than just speaking generally "This email is to verify a request to the security....." we should be specific "This email is to verify a request to add/modify/delete a Webauthn credential" Although I do understand that would require us to verify *every* action separately which is unfeasible. Maybe it would be possible to limit the scope of actions possible for a specific elevation. 
It should be configurable.
The email notification that an event happened should be specific and should already be feasible.

refactor(templates): reword/reformat new email templates

---

docs/content/configuration/identity-providers/openid-connect/clients.md

docs: fix copy/paste typo in access_token_signed_response_alg description

---

docs/content/integration/openid-connect/paperless/index.md

Due to changes in the `django-allauth` dependency in Paperless, the current integration instructions did not work with the latest version of Paperless.
This PR updates the `redirect_uris` parameter in the documentation to fix this.

docs(oidc): update integration documentation for Paperless

---

docs/content/reference/guides/generating-secure-values.md

Was following the tutorial and noticed this small mistake

Remove a curly brace that breaks a command in generating-secure-values.md

---

internal/authentication/ldap_user_provider.go

This fixes an issue where LDAP attribute names are treated as case-sensitive when they normally shouldn't be. This was caused by improvements to the attribute matching pattern which caused a regression.
Fixes #7791

fix(authentication): ldap attributes treated case-sensitive

---

go.mod
go.sum
internal/middlewares/authelia_context.go
internal/model/const.go
internal/oidc/client.go
internal/oidc/client_test.go
internal/oidc/config.go
internal/oidc/config_test.go
internal/oidc/types_test.go
internal/storage/sql_provider.go

This fixes an issue where all JWT assertions are strictly checked against the Token URL. RFC7523 Section 3 states that the JWT must contain an 'aud' claim that identifies the authorization server and that the token endpoint URL may be used, not that it must be used. RFC9126 clarifies this that it should be the issuer value, and that both the token endpoint URL and pushed authorization request endpoint URL must also be accepted. This fix facilitate this. In addition it fixes a log message, and an edge case where using a JWT assertion could trigger a handled panic.

fix(oidc): jwt assertions aud overly strict

---

.buildkite/steps/e2etests.sh

While we debug causes for this suites failure solely on agents we're suspending this suite.

ci: temporarily skip k8s suite

---

internal/suites/example/compose/redis-sentinel/docker-compose.yml
internal/suites/suite_high_availability_test.go

This change adds in appropriate healthchecks and dependencies for the HighAvailability suite and also ensures that the correct node (master) is brought down during integration tests.

fix(suites): container dependencies for redis stack in ha suite

---

web/src/views/LoginPortal/AuthenticatedView/AuthenticatedView.tsx
web/src/views/LoginPortal/SecondFactor/MethodContainer.tsx
web/src/views/LoginPortal/SecondFactor/SecondFactorForm.tsx

When Authelia is configured to only allow Time-based One Time Passwords the layout breaks on a single view, this fixes that issue.

fix(web): ux fix on totp only config

---

.buildkite/hooks/post-checkout
.buildkite/steps/e2etests.sh

This change re-enables the Kubernetes suite and also removes the early pull of the `crossbuild` container as this has now moved up into the agent `environment` hook for earlier priming.
Closes #7923.

ci(buildkite): re-enable kubernetes suite

---

.buildkite/hooks/post-command

This change ensures that the subsequent hooks after the `post-command` hook are not ignored due to a directory change which means hooks no longer can be found at `.buildkite/hooks`.

ci(buildkite): fix pre-exit hook conditionally being ignored

---

api/openapi.yml
internal/oidc/config.go
internal/oidc/config_test.go
internal/oidc/const.go
internal/oidc/discovery.go
internal/oidc/discovery_test.go

This fixes an issue where the 'select_account' prompt is considered invalid.

fix(oidc): select account prompt missing

---

api/index.html
api/openapi.yml
cmd/authelia-scripts/cmd/build.go
internal/middlewares/const.go
internal/middlewares/headers.go
internal/server/asset.go
internal/server/const.go
internal/server/handlers.go
internal/server/template.go
internal/server/template_test.go

This change fixes CSP errors when browsing Swagger and cuts down the binary/image size 10%+ by keeping only required files from the swagger-ui package.

fix: swagger-ui csp and cleanup unnecessary files

---

docs/content/integration/openid-connect/homarr/index.md

Without it the redirect goes to localhost:7575 instead of to the correct domain and the flow fails.
More details in https://github.com/ajnart/homarr/issues/1909

Add NEXTAUTH_URL for homarr config, needed in revese proxy setup

---

docs/content/integration/openid-connect/immich/index.md

Some recent version of Immich changed its callback URL for mobile devices, which breaks OAuth.
The [guide](https://immich.app/docs/administration/oauth/) from Immich said that the redirect URIs are,
- app.immich:///oauth-callback - for logging in with OAuth from the [Mobile App](https://immich.app/docs/features/mobile-app)
- ...

docs:  fix outdated redirect_uris in Immich integration

---

internal/configuration/provider_test.go
internal/configuration/test_resources/config_oidc_empty_jwk_key.yml
internal/configuration/validator/const.go
internal/configuration/validator/identity_providers.go
internal/configuration/validator/identity_providers_test.go

This fixes an issue where not defining the required key for a JSON Web Key would cause a panic.
Fixes #8020

fix(configuration): jwk without required key startup panic

---

docs/content/integration/openid-connect/outline/index.md

Remove the double quotes around the OIDC scope, which cause an error (cf. https://github.com/authelia/authelia/discussions/5671)

Outline: remove error-creating quotes

---

docs/content/integration/openid-connect/oauth-2.0-bearer-token-usage.md

Found this formatting error in [your documentation](https://www.authelia.com/integration/openid-connect/oauth-2.0-bearer-token-usage/).

docs: add missing grave

---

docs/content/configuration/identity-validation/reset-password.md

Hi,
this adds a missing link to the docs reference section on how to generate a secure hmac secret.

docs: add link to reference section on how to generate a secure hmac secret

---

docs/content/integration/openid-connect/frequently-asked-questions.md
docs/content/reference/guides/generating-secure-values.md

Current docker commands won't remove the containers after the secrets are generated. I added the `--rm` argument so that the containers will be removed after the secret gets generated.
https://docs.docker.com/reference/cli/docker/container/run/#rm

Remove docker containers after generating secrets

---

docs/content/integration/openid-connect/mealie/index.md

Hello,
The new release of Mealie (v2.0.0) includes breaking changes to their OpenID Connect implementation:
- Mealie v2.0.0 release notes: https://github.com/mealie-recipes/mealie/releases/tag/v2.0.0
- Mealie PR about the changes: https://github.com/mealie-recipes/mealie/pull/4254
This PR updates the integration documentation.
Thanks,

docs(oidc): mealie v2.0.0

---

docs/content/reference/guides/passwords.md

To not leave lingering containers, it's best to pass `--rm` to the container when generating passwords.

Add `--rm` to Docker commands in passwords.md

---

docs/content/configuration/notifications/smtp.md

Hi,
this updates the Gmail example to use the new address scheme.
The reference to [security] was also missing. I hope I linked it as intended.

docs: update gmail example

---

docs/content/integration/openid-connect/minio/index.md

https://minio.com looks to be a parked domain.
https://min.io is the correct domain.

Fix link to minio

---

docs/content/configuration/first-factor/file.md
docs/content/configuration/first-factor/ldap.md
docs/content/configuration/second-factor/duo.md
docs/content/configuration/session/introduction.md
docs/content/integration/proxies/support.md
docs/content/integration/proxies/swag.md
docs/content/overview/authentication/introduction.md
docs/content/overview/authorization/access-control.md
docs/content/overview/authorization/openid-connect-1.0.md
docs/content/overview/authorization/regulation.md
docs/content/overview/authorization/statelessness.md
docs/content/overview/authorization/trusted-headers.md
docs/content/overview/prologue/architecture/index.md
docs/content/overview/prologue/introduction.md
docs/content/overview/prologue/supported-proxies.md
docs/content/overview/security/introduction.md
docs/content/overview/security/measures.md
docs/content/overview/security/threat-model.md
docs/content/reference/guides/passwords.md
docs/content/reference/guides/proxy-authorization.md
docs/content/reference/guides/server-asset-overrides.md
docs/content/reference/integrations/cache-integrations.md

Hi,
this further extends on #8047. Hopefully, I’ve covered everything now.
I also noticed that the content in some sections of the overview is centered instead of left-aligned. 
To fix this, I enabled the table of contents for all sections in the overview to be consistent with the rest of the documentation.
The missing link [here](https://github.com/authelia/authelia/blob/239fe2d9c3da1ff7f21ee614816d6d3ead994d66/docs/content/overview/security/introduction.md?plain=1#L24) should probably be added by the team to provide a fitting source for authelia.

docs: fix references in callouts & align overview

---

README.md

PR removes extra parentheses in the `.deb package` link of the `README.md` file.

docs: fix broken releases reference

---

docs/content/integration/openid-connect/librechat/index.md

Fix documentation of librechat OIDC integration by:
- fill correct OPENID_ISSUER and OPENID_CALLBACK_URL in dotenv file

documentation: fill correct callback urls into librechat OIDC config

---

internal/handlers/handler_oidc_authorization.go
internal/handlers/handler_oidc_authorization_consent.go
internal/totp/totp.go

This change provides additional information as part of the OIDC authorization requests, this allows simpler debugging if custom authorization policies are being utilised for OIDC clients.

refactor(handlers): log policy and debug info for oidc authorization

---

docs/content/configuration/miscellaneous/introduction.md

It is unclear if adding root certificates to the certificates_directory will allow verification for self-signed certificates for things other than SMTP and LDAP.
This change aims to improve clarity in that regard.

docs: add supported items to certificates_directory docs

---

docs/content/integration/openid-connect/expressjs/index.md

This fixes an oversight in the express.js example.
Closes #8502

docs(oidc): fix express example

---

docs/content/integration/deployment/docker.md
docs/content/integration/proxies/traefik.md

Documentation variables in the traefik integration guide weren't rendered correctly after #8527.

docs: fix traefik integration sitevars

---

internal/configuration/schema/types_address.go
internal/configuration/schema/types_address_test.go
internal/storage/const.go
internal/storage/sql_provider_backend_postgres.go
internal/storage/sql_provider_backend_postgres_test.go

This allows unix sockets to include ports in the address URL. In addition allows for a absolute path for the PostgreSQL socket type. Both options are only used by PostgreSQL but other unix sockets will not expressly error if this is included.
Fixes #8509

fix(configuration): allow unix socket ports

---

internal/server/template.go

This change fixes the rendering of the privacy policy when administrators also have the remember me option enabled in their Authelia instance.
Fixes #8537.

fix(web): include privacy policy when remember me is enabled

---

internal/notification/smtp_notifier.go

This fixes an issue where the SMTP logging fails to serialize a log message with the TLS config in the fields.
Fixes #8569

fix(notifier): smtp log fails to serialize

---

docs/content/integration/openid-connect/dokuwiki/index.md

The current documentation leads to DokuWiki outputting the warning after Authelia login:
> Service did not provide a Refresh Token. You will be logged out when the session expires.
Indeed the session will expire rather soon.
Authelia determined client_secret_post for DokuWiki. DokuWiki requests a refresh token, which requires grant_types and response_type code to be configured.
This PR updates the documentation to propose the correct configuration for DokuWiki.
Tested with Authelia v4.38.18 + DokuWiki 55.2 (as already defined in the Authelia DokuWiki docs page).

docs(oidc): fix dokuwiki oidc configuration

---

docs/content/configuration/identity-providers/openid-connect/provider.md

The type was incorrectly set as `list(string(string))`, and has been updated to `list(list(string))` to match the access control documentation.

docs(oidc): fix type of authorization_policies subject

---

docs/content/configuration/miscellaneous/logging.md
internal/commands/const.go
internal/commands/context.go
internal/commands/services.go
internal/commands/services_test.go
internal/logging/const.go
internal/logging/file.go
internal/logging/logger.go
internal/logging/logger_test.go

This implements a method to send Authelia a SIGHUP signal to indicate it should reload the configuration file. This can be used in two ways. If using an external logrotate service you can tell Authelia to reopen the file and create it if it doesn't exist. Secondly if you use the existing time date replacements this will create a brand new log file with the current time.
Closes #4964

feat(logging): reopen on sighup

---

docs/content/integration/openid-connect/homarr/index.md

the oidc config for homarr was outdated and didn't worked anymore. the part with the automatic permission assignment isn't available anymore. instead a note to the permission sync was added.

fixed homarr oidc connect

---

internal/configuration/schema/configuration.go
internal/configuration/validator/const.go
internal/configuration/validator/theme_test.go
web/src/contexts/ThemeContext.tsx
web/src/themes/Oled.ts
web/src/themes/index.ts

This PR introduces a new OLED theme option that should provide a true black background.
See example screenshots below.
Closes #1935

feat: add new oled theme

---

internal/handlers/func_test.go
internal/handlers/handler_sign_webauthn_test.go

fix test failing due to different call path on local systems vs buildkite

test(handlers): fix failing webauthn test with regex

---

docs/content/reference/guides/metrics.md
internal/metrics/prometheus.go

This adjusts the passkey logins to have a wholly unique metric.

feat(metrics): record passkey logins separately

---

internal/handlers/func_test.go
internal/handlers/handler_firstfactor_passkey.go
internal/handlers/handler_firstfactor_passkey_test.go
internal/handlers/handler_firstfactor_password.go
internal/handlers/handler_sign_webauthn_test.go
internal/mocks/authelia_ctx.go
internal/regulation/regulator_test.go
internal/regulation/util.go

This includes all failures for passkeys as a logged attempt in the auth logs.

refactor(webauthn): log all failures for passkeys

---

docs/content/integration/openid-connect/jellyfin/index.md

This makes it clearer to use the matching oidc start to url to the documented redirect url.
Resolves: #8935

docs: clarify jellyfin oidc start url

---

docs/content/integration/kubernetes/secrets.md

While the key wasn't functional we use this notation for keys to avoid any potential issues and it makes it very clearly non-functional.

docs: remove example key material

---

docs/content/configuration/identity-providers/openid-connect/clients.md

This includes another missing note about implicit consent in which the mode is forced to be explicit if prompting the user for login is requested.

docs: additional note about implicit consent (#9353)

---

docs/content/integration/openid-connect/grafana/index.md

This adds the OpenID Connect 1.0 conformance bug note for claims to Grafana.

docs(oidc): add grafana conformance bug note

---

web/src/components/OneTimeCodeTextField.tsx
web/src/views/Settings/Common/IdentityVerificationDialog.tsx
web/src/views/Settings/TwoFactorAuthentication/OneTimePasswordRegisterDialog.tsx
web/src/views/Settings/TwoFactorAuthentication/WebAuthnCredentialEditDialog.tsx

This pr also moves a couple components to the new `slotProps` from the depreciated `inputProps`.
This is the current format for the identity verification dialog with harder to see buttons and text field.
This is the new one with a different color used for the text box and a different variant for the button.
The color used for the "verify button" was changed to 'info' to ensure the color is consistent across themes.

fix(web): adjust contrast for iv buttons and text input

---

.github/workflows/slsa.yml

This change fixes an incorrect workflow reference and attempts to check the build state before the initial polling of 10 minutes.
Closes #10190.

ci: fix slsa attestation workflow

---

docs/layouts/shortcodes/oidc-common.html

The `$config` value points to the wrong location in the docs tree and the specific links which use the `$config` value point to `.md` files which are incorrect. This results in these two links in every client OIDC doc page to be broken and lead to 404 errors.
* Change the `$config` value to the right location and remove the trailing slash
* Change the specific links to the non `.md` suffixed values
Note that this commit is in the authelia repo instead of the authelia website repo which is where the READMEs indicate this content is meant to be. It's unclear if the READMEs are incorrect or if this file is in the incorrect location. See https://github.com/authelia/authelia/discussions/10339

docs: fix bad path prefix for oidc-common links

---

crowdin.yml

This change updates i18n pull requests from Crowdin to include the language name in the title.

i18n: update pr title to include language
